/* Auto-generated by tool/gen_usdt_bindings.rb. Do not edit. */
#ifndef RUBY_PROBES_BRIDGE_H
#define RUBY_PROBES_BRIDGE_H

#include <stddef.h>
#include <stdint.h>
#include "ruby/internal/attr/noinline.h"
#include "ruby/internal/dllexport.h"

RBIMPL_SYMBOL_EXPORT_BEGIN()

int rb_usdt_method_entry_enabled(void);
void rb_usdt_method_entry(const char * classname, const char * methodname, const char * filename, int lineno);

int rb_usdt_method_return_enabled(void);
void rb_usdt_method_return(const char * classname, const char * methodname, const char * filename, int lineno);

int rb_usdt_cmethod_entry_enabled(void);
void rb_usdt_cmethod_entry(const char * classname, const char * methodname, const char * filename, int lineno);

int rb_usdt_cmethod_return_enabled(void);
void rb_usdt_cmethod_return(const char * classname, const char * methodname, const char * filename, int lineno);

int rb_usdt_require_entry_enabled(void);
void rb_usdt_require_entry(const char * rquiredfile, const char * filename, int lineno);

int rb_usdt_require_return_enabled(void);
void rb_usdt_require_return(const char * requiredfile, const char * filename, int lineno);

int rb_usdt_find_require_entry_enabled(void);
void rb_usdt_find_require_entry(const char * requiredfile, const char * filename, int lineno);

int rb_usdt_find_require_return_enabled(void);
void rb_usdt_find_require_return(const char * requiredfile, const char * filename, int lineno);

int rb_usdt_load_entry_enabled(void);
void rb_usdt_load_entry(const char * loadedfile, const char * filename, int lineno);

int rb_usdt_load_return_enabled(void);
void rb_usdt_load_return(const char * loadedfile, const char * filename, int lineno);

int rb_usdt_raise_enabled(void);
void rb_usdt_raise(const char * classname, const char * filename, int lineno);

int rb_usdt_object_create_enabled(void);
void rb_usdt_object_create(const char * classname, const char * filename, int lineno);

int rb_usdt_array_create_enabled(void);
void rb_usdt_array_create(long length, const char * filename, int lineno);

int rb_usdt_hash_create_enabled(void);
void rb_usdt_hash_create(long length, const char * filename, int lineno);

int rb_usdt_string_create_enabled(void);
void rb_usdt_string_create(long length, const char * filename, int lineno);

int rb_usdt_symbol_create_enabled(void);
void rb_usdt_symbol_create(const char * str, const char * filename, int lineno);

int rb_usdt_parse_begin_enabled(void);
void rb_usdt_parse_begin(const char * sourcefile, int lineno);

int rb_usdt_parse_end_enabled(void);
void rb_usdt_parse_end(const char * sourcefile, int lineno);

int rb_usdt_insn_enabled(void);
void rb_usdt_insn(const char * insns_name);

int rb_usdt_insn_operand_enabled(void);
void rb_usdt_insn_operand(const char * val, const char * insns_name);

int rb_usdt_gc_mark_begin_enabled(void);
void rb_usdt_gc_mark_begin(void);

int rb_usdt_gc_mark_end_enabled(void);
void rb_usdt_gc_mark_end(void);

int rb_usdt_gc_sweep_begin_enabled(void);
void rb_usdt_gc_sweep_begin(void);

int rb_usdt_gc_sweep_end_enabled(void);
void rb_usdt_gc_sweep_end(void);

int rb_usdt_gc_enter_enabled(void);
void rb_usdt_gc_enter(int event);

int rb_usdt_gc_exit_enabled(void);
void rb_usdt_gc_exit(int event);

int rb_usdt_gc_mark_stacked_objects_enabled(void);
void rb_usdt_gc_mark_stacked_objects(size_t popped_count);

int rb_usdt_gc_sweep_page_enabled(void);
void rb_usdt_gc_sweep_page(int slot_size, int final_slots, int freed_slots, int empty_slots);

int rb_usdt_gc_obj_new_enabled(void);
void rb_usdt_gc_obj_new(void * obj, uintptr_t flags);

int rb_usdt_gc_obj_free_enabled(void);
void rb_usdt_gc_obj_free(void * obj, uintptr_t flags);

int rb_usdt_gc_xmalloc_enabled(void);
void rb_usdt_gc_xmalloc(size_t n, size_t size);

int rb_usdt_gc_xcalloc_enabled(void);
void rb_usdt_gc_xcalloc(size_t n, size_t size);

int rb_usdt_gc_xfree_enabled(void);
void rb_usdt_gc_xfree(void * obj, size_t size);

int rb_usdt_gvl_acquire_enabled(void);
void rb_usdt_gvl_acquire(void);

int rb_usdt_gvl_release_enabled(void);
void rb_usdt_gvl_release(void);

int rb_usdt_rts_set_running_enabled(void);
void rb_usdt_rts_set_running(void * sched, void * old_thread, void * new_thread);

RBIMPL_SYMBOL_EXPORT_END()

#endif /* RUBY_PROBES_BRIDGE_H */
