/* Auto-generated by tool/gen_usdt_bindings.rb. Do not edit. */
#include "probes.h"
#include "probes_bridge.h"

RBIMPL_SYMBOL_EXPORT_BEGIN()

int rb_usdt_method_entry_enabled(void) {
#ifdef RUBY_DTRACE_METHOD_ENTRY_ENABLED
    return RUBY_DTRACE_METHOD_ENTRY_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_method_entry(const char * classname, const char * methodname, const char * filename, int lineno) {
#ifdef RUBY_DTRACE_METHOD_ENTRY
    RUBY_DTRACE_METHOD_ENTRY(classname, methodname, filename, lineno);
#endif
}

int rb_usdt_method_return_enabled(void) {
#ifdef RUBY_DTRACE_METHOD_RETURN_ENABLED
    return RUBY_DTRACE_METHOD_RETURN_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_method_return(const char * classname, const char * methodname, const char * filename, int lineno) {
#ifdef RUBY_DTRACE_METHOD_RETURN
    RUBY_DTRACE_METHOD_RETURN(classname, methodname, filename, lineno);
#endif
}

int rb_usdt_cmethod_entry_enabled(void) {
#ifdef RUBY_DTRACE_CMETHOD_ENTRY_ENABLED
    return RUBY_DTRACE_CMETHOD_ENTRY_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_cmethod_entry(const char * classname, const char * methodname, const char * filename, int lineno) {
#ifdef RUBY_DTRACE_CMETHOD_ENTRY
    RUBY_DTRACE_CMETHOD_ENTRY(classname, methodname, filename, lineno);
#endif
}

int rb_usdt_cmethod_return_enabled(void) {
#ifdef RUBY_DTRACE_CMETHOD_RETURN_ENABLED
    return RUBY_DTRACE_CMETHOD_RETURN_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_cmethod_return(const char * classname, const char * methodname, const char * filename, int lineno) {
#ifdef RUBY_DTRACE_CMETHOD_RETURN
    RUBY_DTRACE_CMETHOD_RETURN(classname, methodname, filename, lineno);
#endif
}

int rb_usdt_require_entry_enabled(void) {
#ifdef RUBY_DTRACE_REQUIRE_ENTRY_ENABLED
    return RUBY_DTRACE_REQUIRE_ENTRY_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_require_entry(const char * rquiredfile, const char * filename, int lineno) {
#ifdef RUBY_DTRACE_REQUIRE_ENTRY
    RUBY_DTRACE_REQUIRE_ENTRY(rquiredfile, filename, lineno);
#endif
}

int rb_usdt_require_return_enabled(void) {
#ifdef RUBY_DTRACE_REQUIRE_RETURN_ENABLED
    return RUBY_DTRACE_REQUIRE_RETURN_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_require_return(const char * requiredfile, const char * filename, int lineno) {
#ifdef RUBY_DTRACE_REQUIRE_RETURN
    RUBY_DTRACE_REQUIRE_RETURN(requiredfile, filename, lineno);
#endif
}

int rb_usdt_find_require_entry_enabled(void) {
#ifdef RUBY_DTRACE_FIND_REQUIRE_ENTRY_ENABLED
    return RUBY_DTRACE_FIND_REQUIRE_ENTRY_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_find_require_entry(const char * requiredfile, const char * filename, int lineno) {
#ifdef RUBY_DTRACE_FIND_REQUIRE_ENTRY
    RUBY_DTRACE_FIND_REQUIRE_ENTRY(requiredfile, filename, lineno);
#endif
}

int rb_usdt_find_require_return_enabled(void) {
#ifdef RUBY_DTRACE_FIND_REQUIRE_RETURN_ENABLED
    return RUBY_DTRACE_FIND_REQUIRE_RETURN_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_find_require_return(const char * requiredfile, const char * filename, int lineno) {
#ifdef RUBY_DTRACE_FIND_REQUIRE_RETURN
    RUBY_DTRACE_FIND_REQUIRE_RETURN(requiredfile, filename, lineno);
#endif
}

int rb_usdt_load_entry_enabled(void) {
#ifdef RUBY_DTRACE_LOAD_ENTRY_ENABLED
    return RUBY_DTRACE_LOAD_ENTRY_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_load_entry(const char * loadedfile, const char * filename, int lineno) {
#ifdef RUBY_DTRACE_LOAD_ENTRY
    RUBY_DTRACE_LOAD_ENTRY(loadedfile, filename, lineno);
#endif
}

int rb_usdt_load_return_enabled(void) {
#ifdef RUBY_DTRACE_LOAD_RETURN_ENABLED
    return RUBY_DTRACE_LOAD_RETURN_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_load_return(const char * loadedfile, const char * filename, int lineno) {
#ifdef RUBY_DTRACE_LOAD_RETURN
    RUBY_DTRACE_LOAD_RETURN(loadedfile, filename, lineno);
#endif
}

int rb_usdt_raise_enabled(void) {
#ifdef RUBY_DTRACE_RAISE_ENABLED
    return RUBY_DTRACE_RAISE_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_raise(const char * classname, const char * filename, int lineno) {
#ifdef RUBY_DTRACE_RAISE
    RUBY_DTRACE_RAISE(classname, filename, lineno);
#endif
}

int rb_usdt_object_create_enabled(void) {
#ifdef RUBY_DTRACE_OBJECT_CREATE_ENABLED
    return RUBY_DTRACE_OBJECT_CREATE_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_object_create(const char * classname, const char * filename, int lineno) {
#ifdef RUBY_DTRACE_OBJECT_CREATE
    RUBY_DTRACE_OBJECT_CREATE(classname, filename, lineno);
#endif
}

int rb_usdt_array_create_enabled(void) {
#ifdef RUBY_DTRACE_ARRAY_CREATE_ENABLED
    return RUBY_DTRACE_ARRAY_CREATE_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_array_create(long length, const char * filename, int lineno) {
#ifdef RUBY_DTRACE_ARRAY_CREATE
    RUBY_DTRACE_ARRAY_CREATE(length, filename, lineno);
#endif
}

int rb_usdt_hash_create_enabled(void) {
#ifdef RUBY_DTRACE_HASH_CREATE_ENABLED
    return RUBY_DTRACE_HASH_CREATE_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_hash_create(long length, const char * filename, int lineno) {
#ifdef RUBY_DTRACE_HASH_CREATE
    RUBY_DTRACE_HASH_CREATE(length, filename, lineno);
#endif
}

int rb_usdt_string_create_enabled(void) {
#ifdef RUBY_DTRACE_STRING_CREATE_ENABLED
    return RUBY_DTRACE_STRING_CREATE_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_string_create(long length, const char * filename, int lineno) {
#ifdef RUBY_DTRACE_STRING_CREATE
    RUBY_DTRACE_STRING_CREATE(length, filename, lineno);
#endif
}

int rb_usdt_symbol_create_enabled(void) {
#ifdef RUBY_DTRACE_SYMBOL_CREATE_ENABLED
    return RUBY_DTRACE_SYMBOL_CREATE_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_symbol_create(const char * str, const char * filename, int lineno) {
#ifdef RUBY_DTRACE_SYMBOL_CREATE
    RUBY_DTRACE_SYMBOL_CREATE(str, filename, lineno);
#endif
}

int rb_usdt_parse_begin_enabled(void) {
#ifdef RUBY_DTRACE_PARSE_BEGIN_ENABLED
    return RUBY_DTRACE_PARSE_BEGIN_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_parse_begin(const char * sourcefile, int lineno) {
#ifdef RUBY_DTRACE_PARSE_BEGIN
    RUBY_DTRACE_PARSE_BEGIN(sourcefile, lineno);
#endif
}

int rb_usdt_parse_end_enabled(void) {
#ifdef RUBY_DTRACE_PARSE_END_ENABLED
    return RUBY_DTRACE_PARSE_END_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_parse_end(const char * sourcefile, int lineno) {
#ifdef RUBY_DTRACE_PARSE_END
    RUBY_DTRACE_PARSE_END(sourcefile, lineno);
#endif
}

int rb_usdt_insn_enabled(void) {
#ifdef RUBY_DTRACE_INSN_ENABLED
    return RUBY_DTRACE_INSN_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_insn(const char * insns_name) {
#ifdef RUBY_DTRACE_INSN
    RUBY_DTRACE_INSN(insns_name);
#endif
}

int rb_usdt_insn_operand_enabled(void) {
#ifdef RUBY_DTRACE_INSN_OPERAND_ENABLED
    return RUBY_DTRACE_INSN_OPERAND_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_insn_operand(const char * val, const char * insns_name) {
#ifdef RUBY_DTRACE_INSN_OPERAND
    RUBY_DTRACE_INSN_OPERAND(val, insns_name);
#endif
}

int rb_usdt_gc_mark_begin_enabled(void) {
#ifdef RUBY_DTRACE_GC_MARK_BEGIN_ENABLED
    return RUBY_DTRACE_GC_MARK_BEGIN_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_gc_mark_begin(void) {
#ifdef RUBY_DTRACE_GC_MARK_BEGIN
    RUBY_DTRACE_GC_MARK_BEGIN();
#endif
}

int rb_usdt_gc_mark_end_enabled(void) {
#ifdef RUBY_DTRACE_GC_MARK_END_ENABLED
    return RUBY_DTRACE_GC_MARK_END_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_gc_mark_end(void) {
#ifdef RUBY_DTRACE_GC_MARK_END
    RUBY_DTRACE_GC_MARK_END();
#endif
}

int rb_usdt_gc_sweep_begin_enabled(void) {
#ifdef RUBY_DTRACE_GC_SWEEP_BEGIN_ENABLED
    return RUBY_DTRACE_GC_SWEEP_BEGIN_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_gc_sweep_begin(void) {
#ifdef RUBY_DTRACE_GC_SWEEP_BEGIN
    RUBY_DTRACE_GC_SWEEP_BEGIN();
#endif
}

int rb_usdt_gc_sweep_end_enabled(void) {
#ifdef RUBY_DTRACE_GC_SWEEP_END_ENABLED
    return RUBY_DTRACE_GC_SWEEP_END_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_gc_sweep_end(void) {
#ifdef RUBY_DTRACE_GC_SWEEP_END
    RUBY_DTRACE_GC_SWEEP_END();
#endif
}

int rb_usdt_gc_enter_enabled(void) {
#ifdef RUBY_DTRACE_GC_ENTER_ENABLED
    return RUBY_DTRACE_GC_ENTER_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_gc_enter(int event) {
#ifdef RUBY_DTRACE_GC_ENTER
    RUBY_DTRACE_GC_ENTER(event);
#endif
}

int rb_usdt_gc_exit_enabled(void) {
#ifdef RUBY_DTRACE_GC_EXIT_ENABLED
    return RUBY_DTRACE_GC_EXIT_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_gc_exit(int event) {
#ifdef RUBY_DTRACE_GC_EXIT
    RUBY_DTRACE_GC_EXIT(event);
#endif
}

int rb_usdt_gc_mark_stacked_objects_enabled(void) {
#ifdef RUBY_DTRACE_GC_MARK_STACKED_OBJECTS_ENABLED
    return RUBY_DTRACE_GC_MARK_STACKED_OBJECTS_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_gc_mark_stacked_objects(size_t popped_count) {
#ifdef RUBY_DTRACE_GC_MARK_STACKED_OBJECTS
    RUBY_DTRACE_GC_MARK_STACKED_OBJECTS(popped_count);
#endif
}

int rb_usdt_gc_sweep_page_enabled(void) {
#ifdef RUBY_DTRACE_GC_SWEEP_PAGE_ENABLED
    return RUBY_DTRACE_GC_SWEEP_PAGE_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_gc_sweep_page(int slot_size, int final_slots, int freed_slots, int empty_slots) {
#ifdef RUBY_DTRACE_GC_SWEEP_PAGE
    RUBY_DTRACE_GC_SWEEP_PAGE(slot_size, final_slots, freed_slots, empty_slots);
#endif
}

int rb_usdt_gc_obj_new_enabled(void) {
#ifdef RUBY_DTRACE_GC_OBJ_NEW_ENABLED
    return RUBY_DTRACE_GC_OBJ_NEW_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_gc_obj_new(void * obj, uintptr_t flags) {
#ifdef RUBY_DTRACE_GC_OBJ_NEW
    RUBY_DTRACE_GC_OBJ_NEW(obj, flags);
#endif
}

int rb_usdt_gc_obj_free_enabled(void) {
#ifdef RUBY_DTRACE_GC_OBJ_FREE_ENABLED
    return RUBY_DTRACE_GC_OBJ_FREE_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_gc_obj_free(void * obj, uintptr_t flags) {
#ifdef RUBY_DTRACE_GC_OBJ_FREE
    RUBY_DTRACE_GC_OBJ_FREE(obj, flags);
#endif
}

int rb_usdt_gc_xmalloc_enabled(void) {
#ifdef RUBY_DTRACE_GC_XMALLOC_ENABLED
    return RUBY_DTRACE_GC_XMALLOC_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_gc_xmalloc(size_t n, size_t size) {
#ifdef RUBY_DTRACE_GC_XMALLOC
    RUBY_DTRACE_GC_XMALLOC(n, size);
#endif
}

int rb_usdt_gc_xcalloc_enabled(void) {
#ifdef RUBY_DTRACE_GC_XCALLOC_ENABLED
    return RUBY_DTRACE_GC_XCALLOC_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_gc_xcalloc(size_t n, size_t size) {
#ifdef RUBY_DTRACE_GC_XCALLOC
    RUBY_DTRACE_GC_XCALLOC(n, size);
#endif
}

int rb_usdt_gc_xfree_enabled(void) {
#ifdef RUBY_DTRACE_GC_XFREE_ENABLED
    return RUBY_DTRACE_GC_XFREE_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_gc_xfree(void * obj, size_t size) {
#ifdef RUBY_DTRACE_GC_XFREE
    RUBY_DTRACE_GC_XFREE(obj, size);
#endif
}

int rb_usdt_gvl_acquire_enabled(void) {
#ifdef RUBY_DTRACE_GVL_ACQUIRE_ENABLED
    return RUBY_DTRACE_GVL_ACQUIRE_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_gvl_acquire(void) {
#ifdef RUBY_DTRACE_GVL_ACQUIRE
    RUBY_DTRACE_GVL_ACQUIRE();
#endif
}

int rb_usdt_gvl_release_enabled(void) {
#ifdef RUBY_DTRACE_GVL_RELEASE_ENABLED
    return RUBY_DTRACE_GVL_RELEASE_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_gvl_release(void) {
#ifdef RUBY_DTRACE_GVL_RELEASE
    RUBY_DTRACE_GVL_RELEASE();
#endif
}

int rb_usdt_rts_set_running_enabled(void) {
#ifdef RUBY_DTRACE_RTS_SET_RUNNING_ENABLED
    return RUBY_DTRACE_RTS_SET_RUNNING_ENABLED();
#else
    return 0;
#endif
}

void rb_usdt_rts_set_running(void * sched, void * old_thread, void * new_thread) {
#ifdef RUBY_DTRACE_RTS_SET_RUNNING
    RUBY_DTRACE_RTS_SET_RUNNING(sched, old_thread, new_thread);
#endif
}

RBIMPL_SYMBOL_EXPORT_END()
