#ifndef YJIT_H
#define YJIT_H 1

#include "ruby/internal/config.h"
#include "ruby_assert.h" // for RUBY_DEBUG
#include "vm_core.h"
#include "method.h"

#ifndef YJIT_STATS
# define YJIT_STATS (USE_YJIT && RUBY_DEBUG)
#endif

#if USE_YJIT

#if defined(_WIN32) ? defined(_M_AMD64) : (defined(__x86_64__) || defined(__aarch64__))
#else
# error YJIT unsupported platform
#endif

extern unsigned int rb_yjit_call_threshold;
extern unsigned int rb_yjit_cold_threshold;
extern uint64_t rb_yjit_live_iseq_count;
extern uint64_t rb_yjit_iseq_alloc_count;
extern uint64_t rb_yjit_max_compile_time_ns;
extern uint64_t rb_yjit_total_compile_time_ns;
extern bool rb_yjit_enabled_p;
extern bool rb_yjit_compiling_p;

void rb_yjit_invalidate_all_method_lookup_assumptions(void);
void rb_yjit_compile_iseq(const rb_iseq_t *iseq, rb_execution_context_t *ec, bool jit_exception);


/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

/**
 * Free the per-iseq payload
 */
void rb_yjit_iseq_free(const rb_iseq_t* iseq);

/**
 * GC callback for marking GC objects in the per-iseq payload.
 */
void rb_yjit_iseq_mark(void *payload);

/**
 * GC callback for updating GC objects in the per-iseq payload.
 * This is a mirror of [rb_yjit_iseq_mark].
 */
void rb_yjit_iseq_update_references(const rb_iseq_t* iseq);

/**
 * Mark all code memory as writable.
 * This function is useful for garbage collectors that update references in JIT-compiled code in
 * bulk.
 */
void rb_yjit_mark_all_writeable(void);

/**
 * Mark all code memory as executable.
 * This function is useful for garbage collectors that update references in JIT-compiled code in
 * bulk.
 */
void rb_yjit_mark_all_executable(void);

/**
 * Primitive called in yjit.rb
 * Produce a string representing the disassembly for an ISEQ
 */
VALUE rb_yjit_disasm_iseq(rb_execution_context_t* _ec, VALUE _ruby_self, VALUE iseqw);

/**
 * Primitive called in yjit.rb
 * Produce a list of instructions compiled for an isew
 */
VALUE rb_yjit_insns_compiled(rb_execution_context_t* _ec, VALUE _ruby_self, VALUE iseqw);

/**
 * Called when a basic operator is redefined. Note that all the blocks assuming
 * the stability of different operators are invalidated together and we don't
 * do fine-grained tracking.
 */
void rb_yjit_bop_redefined(int klass, enum ruby_basic_operators bop);

/**
 * Callback for when a cme becomes invalid. Invalidate all blocks that depend
 * on the given cme being valid.
 */
void rb_yjit_cme_invalidate(const rb_callable_method_entry_t *callee_cme);

/**
 * Invalidate every block that assumes single-ractor mode. Called when Ruby
 * transitions from single-ractor to multi-ractor mode (i.e. a second ractor
 * is spawned).
 */
void rb_yjit_invalidate_single_ractor(void);

/**
 * Callback for when the global constant state changes.
 */
void rb_yjit_constant_state_changed(ID id);

/**
 * Callback for marking GC objects inside [Invariants].
 * See `struct yjijt_root_struct` in C.
 */
void rb_yjit_root_mark(void);

void rb_yjit_root_update_references(void);

/**
 * Callback from the opt_setinlinecache instruction in the interpreter.
 * Invalidate the block for the matching opt_getinlinecache so it could regenerate code
 * using the new value in the constant cache.
 */
void rb_yjit_constant_ic_update(const rb_iseq_t *iseq, IC ic, unsigned int insn_idx);

/**
 * Invalidate blocks that assume objects of a given class will have no singleton class.
 */
void rb_yjit_invalidate_no_singleton_class(VALUE klass);

/**
 * Invalidate blocks for a given ISEQ that assumes environment pointer is
 * equal to base pointer.
 */
void rb_yjit_invalidate_ep_is_bp(const rb_iseq_t* iseq);

void rb_yjit_tracing_invalidate_all(void);

/**
 * Print YJIT options for `ruby --help`. `width` is width of option parts, and
 * `columns` is indent width of descriptions.
 */
void rb_yjit_show_usage(int help, int highlight, unsigned int width, int columns);

/**
 * Return true if --yjit-c-builtin is given
 */
VALUE rb_yjit_c_builtin_p(rb_execution_context_t* _ec, VALUE _self);

/**
 * Primitive called in yjit.rb
 * Check if stats generation is enabled
 */
VALUE rb_yjit_stats_enabled_p(rb_execution_context_t* _ec, VALUE _ruby_self);

/**
 * Primitive called in yjit.rb
 * Check if stats generation should print at exit
 */
VALUE rb_yjit_print_stats_p(rb_execution_context_t* _ec, VALUE _ruby_self);

/**
 * Primitive called in yjit.rb.
 * Export all YJIT statistics as a Ruby hash.
 */
VALUE rb_yjit_get_stats(rb_execution_context_t* _ec, VALUE _ruby_self, VALUE key);

/**
 * Primitive called in yjit.rb
 *
 * Check if trace_exits generation is enabled.
 */
VALUE rb_yjit_trace_exit_locations_enabled_p(rb_execution_context_t* _ec, VALUE _ruby_self);

/**
 * Call the C function to parse the raw_samples and line_samples
 * into raw, lines, and frames hash for RubyVM::YJIT.exit_locations.
 */
VALUE rb_yjit_get_exit_locations(rb_execution_context_t* _ec, VALUE _ruby_self);

/**
 * Increment a counter by name from the CRuby side
 * Warning: this is not fast because it requires a hash lookup, so don't use in tight loops
 */
void rb_yjit_incr_counter(const char *counter_name);

/**
 * Record the backtrace when a YJIT exit occurs. This functionality requires
 * the --yjit-trace-exits option.
 *
 * This function will fill two Vec's in YjitExitLocations to record the raw samples
 * and line samples. Their length should be the same, however the data stored in
 * them is different.
 */
void rb_yjit_record_exit_stack(const VALUE *exit_pc);

/**
 * Primitive called in yjit.rb. Zero out all the counters.
 */
VALUE rb_yjit_reset_stats_bang(rb_execution_context_t* _ec, VALUE _ruby_self);

void rb_yjit_update_max_compile_time_ns(uint64_t max_compile_time_ns);

void rb_yjit_collect_binding_alloc(void);

void rb_yjit_collect_binding_set(void);

const VALUE *rb_yjit_count_side_exit_op(const VALUE *exit_pc);

/**
 * Parse one command-line option.
 * This is called from ruby.c
 */
bool rb_yjit_parse_option(const char *str_ptr);

bool rb_yjit_option_disable(void);

/**
 * Register specialized codegen for builtin C method entries.
 * Must be called at boot before ruby_init_prelude() since the prelude
 * could redefine core methods (e.g. Kernel.prepend via bundler).
 */
void rb_yjit_init_builtin_cmes(void);

/**
 * This function is called from C code
 */
void rb_yjit_init(bool yjit_enabled);

void rb_yjit_free_at_exit(void);

/**
 * Called from C code to begin compiling a function
 * NOTE: this should be wrapped in RB_VM_LOCK_ENTER(), rb_vm_barrier() on the C side
 * If jit_exception is true, compile JIT code for handling exceptions.
 * See jit_compile_exception() for details.
 */
uint8_t *rb_yjit_iseq_gen_entry_point(const rb_iseq_t* iseq,
                                      rb_execution_context_t* ec,
                                      bool jit_exception);

/**
 * Free and recompile all existing JIT code
 */
VALUE rb_yjit_code_gc(rb_execution_context_t* _ec, VALUE _ruby_self);

/**
 * Enable YJIT compilation, returning true if YJIT was previously disabled
 */
VALUE rb_yjit_enable(rb_execution_context_t* _ec,
                     VALUE _ruby_self,
                     VALUE gen_stats,
                     VALUE print_stats,
                     VALUE gen_log,
                     VALUE print_log,
                     VALUE mem_size,
                     VALUE call_threshold);

/**
 * Simulate a situation where we are out of executable memory
 */
VALUE rb_yjit_simulate_oom_bang(rb_execution_context_t* _ec, VALUE _ruby_self);

/**
 * Push a C method frame if the given PC is supposed to lazily push one.
 * This is called from rb_raise() (at rb_exc_new_str()) and other functions
 * that may make a method call (e.g. rb_to_int()).
 */
void rb_yjit_lazy_push_frame(const VALUE *pc);

/**
 * Primitive called in yjit.rb
 * Check if log generation is enabled
 */
VALUE rb_yjit_log_enabled_p(rb_execution_context_t* _ec, VALUE _ruby_self);

/**
 * Primitive called in yjit.rb.
 * Export all YJIT log entries as a Ruby array.
 */
VALUE rb_yjit_get_log(rb_execution_context_t* _ec, VALUE _ruby_self);

#else
// !USE_YJIT
#define rb_yjit_enabled_p false
#define rb_yjit_compiling_p false
static inline void rb_yjit_incr_counter(const char *counter_name) {}
static inline void rb_yjit_invalidate_all_method_lookup_assumptions(void) {}
static inline void rb_yjit_cme_invalidate(rb_callable_method_entry_t *cme) {}
static inline void rb_yjit_collect_binding_alloc(void) {}
static inline void rb_yjit_collect_binding_set(void) {}
static inline void rb_yjit_compile_iseq(const rb_iseq_t *iseq, rb_execution_context_t *ec, bool jit_exception) {}
static inline void rb_yjit_init_builtin_cmes(void) {}
static inline void rb_yjit_init(bool yjit_enabled) {}
static inline void rb_yjit_bop_redefined(int redefined_flag, enum ruby_basic_operators bop) {}
static inline void rb_yjit_constant_state_changed(ID id) {}
static inline void rb_yjit_iseq_mark(void *payload) {}
static inline void rb_yjit_iseq_update_references(const rb_iseq_t *iseq) {}
static inline void rb_yjit_iseq_free(const rb_iseq_t *iseq) {}
static inline void rb_yjit_invalidate_single_ractor(void) {}
static inline void rb_yjit_constant_ic_update(const rb_iseq_t *const iseq, IC ic, unsigned insn_idx) {}
static inline void rb_yjit_tracing_invalidate_all(void) {}
static inline void rb_yjit_lazy_push_frame(const VALUE *pc) {}
static inline void rb_yjit_invalidate_no_singleton_class(VALUE klass) {}
static inline void rb_yjit_invalidate_ep_is_bp(const rb_iseq_t *iseq) {}
#endif // #if USE_YJIT

#endif // YJIT_H
