#ifndef ZJIT_H
#define ZJIT_H 1

#include "shape.h" // for shape_id_t

#ifndef ZJIT_STATS
# define ZJIT_STATS (USE_ZJIT && RUBY_DEBUG)
#endif

typedef struct zjit_jit_frame {
    const VALUE *pc;
    const rb_iseq_t *iseq;
    bool materialize_block_code;
    uint32_t stack_size;
    VALUE stack[];
} zjit_jit_frame_t;

#if USE_ZJIT

#define ZJIT_STACK_MAP_VREG_TAG 0x08
#define ZJIT_STACK_MAP_SKIP_TAG 0x10
#define ZJIT_STACK_MAP_BASE_PTR_TAG 0x18
#define ZJIT_STACK_MAP_TAG_MASK 0xff
#define ZJIT_STACK_MAP_SHIFT 8

#define ZJIT_STACK_MAP_BASE_PTR_SIZE_SHIFT 32
#define ZJIT_STACK_MAP_BASE_PTR_INDEX_MASK 0xffffff

static inline bool
ZJIT_STACK_MAP_VREG_P(VALUE entry)
{
    return (entry & ZJIT_STACK_MAP_TAG_MASK) == ZJIT_STACK_MAP_VREG_TAG;
}

static inline size_t
ZJIT_STACK_MAP_VREG_INDEX(VALUE entry)
{
    return entry >> ZJIT_STACK_MAP_SHIFT;
}

static inline bool
ZJIT_STACK_MAP_SKIP_P(VALUE entry)
{
    return (entry & ZJIT_STACK_MAP_TAG_MASK) == ZJIT_STACK_MAP_SKIP_TAG;
}

static inline size_t
ZJIT_STACK_MAP_SKIP_SIZE(VALUE entry)
{
    return entry >> ZJIT_STACK_MAP_SHIFT;
}

static inline bool
ZJIT_STACK_MAP_BASE_PTR_P(VALUE entry)
{
    return (entry & ZJIT_STACK_MAP_TAG_MASK) == ZJIT_STACK_MAP_BASE_PTR_TAG;
}

static inline size_t
ZJIT_STACK_MAP_BASE_PTR_SLOT_INDEX(VALUE entry)
{
    return (entry >> ZJIT_STACK_MAP_SHIFT) & ZJIT_STACK_MAP_BASE_PTR_INDEX_MASK;
}

static inline size_t
ZJIT_STACK_MAP_BASE_PTR_STACK_SIZE(VALUE entry)
{
    return entry >> ZJIT_STACK_MAP_BASE_PTR_SIZE_SHIFT;
}

extern void *rb_zjit_entry;
extern bool rb_zjit_compiling_p;
extern const zjit_jit_frame_t rb_zjit_c_frame;
extern unsigned int rb_zjit_call_threshold;
extern unsigned int rb_zjit_profile_threshold;

void rb_zjit_compile_iseq(const rb_iseq_t *iseq, rb_execution_context_t *ec, bool jit_exception);
void rb_zjit_profile_enable(const rb_iseq_t *iseq);
void rb_zjit_materialize_frames_for_longjmp(const rb_execution_context_t *ec, rb_control_frame_t *cfp);


/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

/**
 * Initialize IDs and annotate builtin C method entries.
 * Must be called at boot before ruby_init_prelude() since the prelude
 * could redefine core methods (e.g. Kernel.prepend via bundler).
 */
void rb_zjit_init_builtin_cmes(void);

/**
 * Initialize ZJIT at boot. This is called even if ZJIT is disabled.
 */
void rb_zjit_init(bool zjit_enabled);

/**
 * Enable ZJIT compilation, returning Qtrue if ZJIT was previously disabled
 */
VALUE rb_zjit_enable(rb_execution_context_t* _ec, VALUE _self);

/**
 * Assert that any future ZJIT compilation will return a function pointer (not fail to compile)
 */
VALUE rb_zjit_assert_compiles(rb_execution_context_t* _ec, VALUE _self);

/**
 * Record a backtrace with ZJIT side exits as a Perfetto trace event
 */
void rb_zjit_record_exit_stack(const char *reason);

/**
 * Record a backtrace with ZJIT fallbacks as a Perfetto trace event
 */
void rb_zjit_record_fallback_stack(const char *reason);

/**
 * CRuby API to compile a given ISEQ.
 * If jit_exception is true, compile JIT code for handling exceptions.
 * See jit_compile_exception() for details.
 */
uint8_t *rb_zjit_iseq_gen_entry_point(const rb_iseq_t* iseq,
                                      rb_execution_context_t* ec,
                                      bool jit_exception);

extern bool rb_zjit_newobj_hook_enabled_p(void);

/**
 * Primitive called in zjit.rb. Zero out all the counters.
 */
VALUE rb_zjit_reset_stats_bang(rb_execution_context_t* _ec, VALUE _self);

/**
 * Return a Hash object that contains ZJIT statistics
 */
VALUE rb_zjit_stats(rb_execution_context_t* _ec, VALUE _self, VALUE target_key);

/**
 * Primitive called in zjit.rb
 *
 * Check if trace_exits generation is enabled.
 */
VALUE rb_zjit_trace_exit_locations_enabled_p(rb_execution_context_t* _ec, VALUE _ruby_self);

/**
 * Set default values to ZJIT options. Setting Some to OPTIONS will make `#with_jit`
 * enable the JIT hook while not enabling compilation yet.
 */
void rb_zjit_prepare_options(void);

/**
 * Parse a --zjit* command-line flag
 */
bool rb_zjit_parse_option(const char *str_ptr);

/**
 * Print ZJIT options for `ruby --help`. `width` is width of option parts, and
 * `columns` is indent width of descriptions.
 */
void rb_zjit_show_usage(int help, int highlight, unsigned int width, int columns);

/**
 * Return true if ZJIT should be enabled at boot.
 */
bool rb_zjit_option_enable(void);

/**
 * Return Qtrue if --zjit-stats has been specified.
 */
VALUE rb_zjit_stats_enabled_p(rb_execution_context_t* _ec, VALUE _self);

/**
 * Return Qtrue if stats should be printed at exit.
 */
VALUE rb_zjit_print_stats_p(rb_execution_context_t* _ec, VALUE _self);

/**
 * Return path if stats should be printed at exit to a specified file, else Qnil.
 */
VALUE rb_zjit_get_stats_file_path_p(rb_execution_context_t* _ec, VALUE _self);

/**
 * API called from zjit_* instruction. opcode is the bare (non-zjit_*) instruction.
 */
void rb_zjit_profile_insn(uint32_t bare_opcode, rb_execution_context_t* ec);

/**
 * Called when a basic operator is redefined. Note that all the blocks assuming
 * the stability of different operators are invalidated together and we don't
 * do fine-grained tracking.
 */
void rb_zjit_bop_redefined(int klass, enum ruby_basic_operators bop);

/**
 * Invalidate blocks for a given ISEQ that assumes environment pointer is
 * equal to base pointer.
 */
void rb_zjit_invalidate_no_ep_escape(const rb_iseq_t* iseq);

/**
 * Called when a method is redefined. Invalidates all JIT code that depends on the CME.
 */
void rb_zjit_cme_invalidate(const rb_callable_method_entry_t *cme);

/**
 * Called when a constant is redefined. Invalidates all JIT code that depends on the constant.
 */
void rb_zjit_constant_state_changed(ID id);

/**
 * Invalidate every block that assumes single-ractor mode. Called when Ruby
 * transitions from single-ractor to multi-ractor mode (i.e. a second ractor
 * is spawned).
 */
void rb_zjit_invalidate_single_ractor(void);

void rb_zjit_tracing_invalidate_all(void);

/**
 * Callback for when a NEWOBJ internal event hook is enabled. The inline
 * allocation fast path bypasses rb_newobj, so it never fires NEWOBJ; invalidate
 * every block that assumed no such hook was active so it falls back to the
 * interpreter, which fires the event.
 */
void rb_zjit_invalidate_newobj_hook(void);

/**
 * Callback for when a non-root box is created. In that case we need to
 * invalidate every block that assumes root-box-only mode.
 */
void rb_zjit_invalidate_root_box(void);

void rb_zjit_invalidate_no_singleton_class(VALUE klass);

/**
 * GC callback for marking GC objects in the per-ISEQ payload.
 */
void rb_zjit_iseq_mark(void *payload);

/**
 * GC callback for updating GC objects in the per-ISEQ payload.
 */
void rb_zjit_iseq_update_references(void *payload);

/**
 * GC callback for finalizing an ISEQ
 */
void rb_zjit_iseq_free(const rb_iseq_t* iseq);

/**
 * GC callback for finalizing a CME
 */
void rb_zjit_cme_free(const rb_callable_method_entry_t *cme);

/**
 * GC callback for finalizing a class
 */
void rb_zjit_klass_free(VALUE klass);

/**
 * GC callback for updating object references after all object moves
 */
void rb_zjit_root_update_references(void);

/**
 * GC callback for making all JIT code writable before updating references in bulk.
 * This avoids toggling W^X permissions per-page during GC compaction.
 */
void rb_zjit_mark_all_writable(void);

/**
 * GC callback for making all JIT code executable after updating references in bulk.
 */
void rb_zjit_mark_all_executable(void);

/**
 * Callback for marking GC objects inside [crate::invariants::Invariants].
 */
void rb_zjit_root_mark(void);

/**
 * Update the iseq pointer in an on-stack JITFrame during GC compaction.
 * Called from rb_execution_context_update in vm.c.
 */
void rb_zjit_jit_frame_update_references(zjit_jit_frame_t *jit_frame);

#define ZJIT_JIT_RETURN_C_FRAME 0x1

static inline const zjit_jit_frame_t *
CFP_ZJIT_FRAME(const rb_control_frame_t *cfp)
{
    if ((VALUE)cfp->jit_return == ZJIT_JIT_RETURN_C_FRAME) {
        return &rb_zjit_c_frame;
    }
    else {
        return (const zjit_jit_frame_t *)((VALUE *)cfp->jit_return)[-1];
    }
}
#else
#define rb_zjit_entry 0
#define rb_zjit_compiling_p false
static inline void rb_zjit_compile_iseq(const rb_iseq_t *iseq, rb_execution_context_t *ec, bool jit_exception) {}
static inline void rb_zjit_profile_insn(uint32_t insn, rb_execution_context_t *ec) {}
static inline void rb_zjit_profile_enable(const rb_iseq_t *iseq) {}
static inline void rb_zjit_bop_redefined(int redefined_flag, enum ruby_basic_operators bop) {}
static inline void rb_zjit_cme_invalidate(const rb_callable_method_entry_t *cme) {}
static inline void rb_zjit_invalidate_no_ep_escape(const rb_iseq_t *iseq) {}
static inline void rb_zjit_constant_state_changed(ID id) {}
static inline void rb_zjit_invalidate_single_ractor(void) {}
static inline void rb_zjit_tracing_invalidate_all(void) {}
static inline void rb_zjit_invalidate_newobj_hook(void) {}
static inline void rb_zjit_invalidate_no_singleton_class(VALUE klass) {}
static inline void rb_zjit_invalidate_root_box(void) {}
static inline void rb_zjit_jit_frame_update_references(zjit_jit_frame_t *jit_frame) {}
static inline void rb_zjit_materialize_frames(const rb_execution_context_t *ec, rb_control_frame_t *cfp) {}
static inline void rb_zjit_materialize_frames_for_longjmp(const rb_execution_context_t *ec, rb_control_frame_t *cfp) {}
static inline const zjit_jit_frame_t *CFP_ZJIT_FRAME(const rb_control_frame_t *cfp) { return NULL; }
#endif // #if USE_ZJIT

#define rb_zjit_enabled_p (rb_zjit_entry != 0)

static inline bool
CFP_ZJIT_FRAME_P(const rb_control_frame_t *cfp)
{
    if (!rb_zjit_enabled_p) return false;
    return cfp->jit_return != NULL;
}

static inline const VALUE*
CFP_PC(const rb_control_frame_t *cfp)
{
    if (CFP_ZJIT_FRAME_P(cfp)) {
        return CFP_ZJIT_FRAME(cfp)->pc;
    }
    return cfp->pc;
}

static inline const rb_iseq_t*
CFP_ISEQ(const rb_control_frame_t *cfp)
{
    if (CFP_ZJIT_FRAME_P(cfp)) {
        return CFP_ZJIT_FRAME(cfp)->iseq;
    }
    return cfp->_iseq;
}

#endif // ZJIT_H
