/* Auto-generated by tool/gen_usdt_bindings.rb. Do not edit. */
//! Rust USDT probe bindings for core_rs
//! Provides zero-cost, type-safe Rust abstractions for USDT dynamic tracing.

pub trait AsCStrPtr {
    fn with_c_str_ptr<R, F: FnOnce(*const core::ffi::c_char) -> R>(&self, f: F) -> R;
}

impl AsCStrPtr for *const core::ffi::c_char {
    #[inline(always)]
    fn with_c_str_ptr<R, F: FnOnce(*const core::ffi::c_char) -> R>(&self, f: F) -> R {
        f(*self)
    }
}

impl AsCStrPtr for *mut core::ffi::c_char {
    #[inline(always)]
    fn with_c_str_ptr<R, F: FnOnce(*const core::ffi::c_char) -> R>(&self, f: F) -> R {
        f(*self as *const core::ffi::c_char)
    }
}

impl AsCStrPtr for &core::ffi::CStr {
    #[inline(always)]
    fn with_c_str_ptr<R, F: FnOnce(*const core::ffi::c_char) -> R>(&self, f: F) -> R {
        f(self.as_ptr())
    }
}

impl AsCStrPtr for &str {
    #[inline(always)]
    fn with_c_str_ptr<R, F: FnOnce(*const core::ffi::c_char) -> R>(&self, f: F) -> R {
        let bytes = self.as_bytes();
        if !bytes.is_empty() && bytes[bytes.len() - 1] == 0 {
            f(bytes.as_ptr() as *const core::ffi::c_char)
        } else {
            let mut buf = [0u8; 256];
            let len = bytes.len().min(255);
            buf[..len].copy_from_slice(&bytes[..len]);
            buf[len] = 0;
            f(buf.as_ptr() as *const core::ffi::c_char)
        }
    }
}

impl AsCStrPtr for &[u8] {
    #[inline(always)]
    fn with_c_str_ptr<R, F: FnOnce(*const core::ffi::c_char) -> R>(&self, f: F) -> R {
        if !self.is_empty() && self[self.len() - 1] == 0 {
            f(self.as_ptr() as *const core::ffi::c_char)
        } else {
            let mut buf = [0u8; 256];
            let len = self.len().min(255);
            buf[..len].copy_from_slice(&self[..len]);
            buf[len] = 0;
            f(buf.as_ptr() as *const core::ffi::c_char)
        }
    }
}

unsafe extern "C" {
    pub fn rb_usdt_method_entry_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_method_entry(classname: *const core::ffi::c_char, methodname: *const core::ffi::c_char, filename: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_method_return_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_method_return(classname: *const core::ffi::c_char, methodname: *const core::ffi::c_char, filename: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_cmethod_entry_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_cmethod_entry(classname: *const core::ffi::c_char, methodname: *const core::ffi::c_char, filename: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_cmethod_return_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_cmethod_return(classname: *const core::ffi::c_char, methodname: *const core::ffi::c_char, filename: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_require_entry_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_require_entry(rquiredfile: *const core::ffi::c_char, filename: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_require_return_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_require_return(requiredfile: *const core::ffi::c_char, filename: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_find_require_entry_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_find_require_entry(requiredfile: *const core::ffi::c_char, filename: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_find_require_return_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_find_require_return(requiredfile: *const core::ffi::c_char, filename: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_load_entry_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_load_entry(loadedfile: *const core::ffi::c_char, filename: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_load_return_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_load_return(loadedfile: *const core::ffi::c_char, filename: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_raise_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_raise(classname: *const core::ffi::c_char, filename: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_object_create_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_object_create(classname: *const core::ffi::c_char, filename: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_array_create_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_array_create(length: core::ffi::c_long, filename: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_hash_create_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_hash_create(length: core::ffi::c_long, filename: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_string_create_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_string_create(length: core::ffi::c_long, filename: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_symbol_create_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_symbol_create(str: *const core::ffi::c_char, filename: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_parse_begin_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_parse_begin(sourcefile: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_parse_end_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_parse_end(sourcefile: *const core::ffi::c_char, lineno: core::ffi::c_int);
    pub fn rb_usdt_insn_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_insn(insns_name: *const core::ffi::c_char);
    pub fn rb_usdt_insn_operand_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_insn_operand(val: *const core::ffi::c_char, insns_name: *const core::ffi::c_char);
    pub fn rb_usdt_gc_mark_begin_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_gc_mark_begin();
    pub fn rb_usdt_gc_mark_end_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_gc_mark_end();
    pub fn rb_usdt_gc_sweep_begin_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_gc_sweep_begin();
    pub fn rb_usdt_gc_sweep_end_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_gc_sweep_end();
    pub fn rb_usdt_gc_enter_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_gc_enter(event: core::ffi::c_int);
    pub fn rb_usdt_gc_exit_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_gc_exit(event: core::ffi::c_int);
    pub fn rb_usdt_gc_mark_stacked_objects_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_gc_mark_stacked_objects(popped_count: usize);
    pub fn rb_usdt_gc_sweep_page_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_gc_sweep_page(slot_size: core::ffi::c_int, final_slots: core::ffi::c_int, freed_slots: core::ffi::c_int, empty_slots: core::ffi::c_int);
    pub fn rb_usdt_gc_obj_new_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_gc_obj_new(obj: *const core::ffi::c_void, flags: usize);
    pub fn rb_usdt_gc_obj_free_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_gc_obj_free(obj: *const core::ffi::c_void, flags: usize);
    pub fn rb_usdt_gc_xmalloc_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_gc_xmalloc(n: usize, size: usize);
    pub fn rb_usdt_gc_xcalloc_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_gc_xcalloc(n: usize, size: usize);
    pub fn rb_usdt_gc_xfree_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_gc_xfree(obj: *const core::ffi::c_void, size: usize);
    pub fn rb_usdt_gvl_acquire_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_gvl_acquire();
    pub fn rb_usdt_gvl_release_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_gvl_release();
    pub fn rb_usdt_rts_set_running_enabled() -> core::ffi::c_int;
    pub fn rb_usdt_rts_set_running(sched: *const core::ffi::c_void, old_thread: *const core::ffi::c_void, new_thread: *const core::ffi::c_void);
}

#[inline(always)]
pub fn method_entry_enabled() -> bool {
    unsafe { rb_usdt_method_entry_enabled() != 0 }
}

#[inline(always)]
pub fn method_return_enabled() -> bool {
    unsafe { rb_usdt_method_return_enabled() != 0 }
}

#[inline(always)]
pub fn cmethod_entry_enabled() -> bool {
    unsafe { rb_usdt_cmethod_entry_enabled() != 0 }
}

#[inline(always)]
pub fn cmethod_return_enabled() -> bool {
    unsafe { rb_usdt_cmethod_return_enabled() != 0 }
}

#[inline(always)]
pub fn require_entry_enabled() -> bool {
    unsafe { rb_usdt_require_entry_enabled() != 0 }
}

#[inline(always)]
pub fn require_return_enabled() -> bool {
    unsafe { rb_usdt_require_return_enabled() != 0 }
}

#[inline(always)]
pub fn find_require_entry_enabled() -> bool {
    unsafe { rb_usdt_find_require_entry_enabled() != 0 }
}

#[inline(always)]
pub fn find_require_return_enabled() -> bool {
    unsafe { rb_usdt_find_require_return_enabled() != 0 }
}

#[inline(always)]
pub fn load_entry_enabled() -> bool {
    unsafe { rb_usdt_load_entry_enabled() != 0 }
}

#[inline(always)]
pub fn load_return_enabled() -> bool {
    unsafe { rb_usdt_load_return_enabled() != 0 }
}

#[inline(always)]
pub fn raise_enabled() -> bool {
    unsafe { rb_usdt_raise_enabled() != 0 }
}

#[inline(always)]
pub fn object_create_enabled() -> bool {
    unsafe { rb_usdt_object_create_enabled() != 0 }
}

#[inline(always)]
pub fn array_create_enabled() -> bool {
    unsafe { rb_usdt_array_create_enabled() != 0 }
}

#[inline(always)]
pub fn hash_create_enabled() -> bool {
    unsafe { rb_usdt_hash_create_enabled() != 0 }
}

#[inline(always)]
pub fn string_create_enabled() -> bool {
    unsafe { rb_usdt_string_create_enabled() != 0 }
}

#[inline(always)]
pub fn symbol_create_enabled() -> bool {
    unsafe { rb_usdt_symbol_create_enabled() != 0 }
}

#[inline(always)]
pub fn parse_begin_enabled() -> bool {
    unsafe { rb_usdt_parse_begin_enabled() != 0 }
}

#[inline(always)]
pub fn parse_end_enabled() -> bool {
    unsafe { rb_usdt_parse_end_enabled() != 0 }
}

#[inline(always)]
pub fn insn_enabled() -> bool {
    unsafe { rb_usdt_insn_enabled() != 0 }
}

#[inline(always)]
pub fn insn_operand_enabled() -> bool {
    unsafe { rb_usdt_insn_operand_enabled() != 0 }
}

#[inline(always)]
pub fn gc_mark_begin_enabled() -> bool {
    unsafe { rb_usdt_gc_mark_begin_enabled() != 0 }
}

#[inline(always)]
pub fn gc_mark_end_enabled() -> bool {
    unsafe { rb_usdt_gc_mark_end_enabled() != 0 }
}

#[inline(always)]
pub fn gc_sweep_begin_enabled() -> bool {
    unsafe { rb_usdt_gc_sweep_begin_enabled() != 0 }
}

#[inline(always)]
pub fn gc_sweep_end_enabled() -> bool {
    unsafe { rb_usdt_gc_sweep_end_enabled() != 0 }
}

#[inline(always)]
pub fn gc_enter_enabled() -> bool {
    unsafe { rb_usdt_gc_enter_enabled() != 0 }
}

#[inline(always)]
pub fn gc_exit_enabled() -> bool {
    unsafe { rb_usdt_gc_exit_enabled() != 0 }
}

#[inline(always)]
pub fn gc_mark_stacked_objects_enabled() -> bool {
    unsafe { rb_usdt_gc_mark_stacked_objects_enabled() != 0 }
}

#[inline(always)]
pub fn gc_sweep_page_enabled() -> bool {
    unsafe { rb_usdt_gc_sweep_page_enabled() != 0 }
}

#[inline(always)]
pub fn gc_obj_new_enabled() -> bool {
    unsafe { rb_usdt_gc_obj_new_enabled() != 0 }
}

#[inline(always)]
pub fn gc_obj_free_enabled() -> bool {
    unsafe { rb_usdt_gc_obj_free_enabled() != 0 }
}

#[inline(always)]
pub fn gc_xmalloc_enabled() -> bool {
    unsafe { rb_usdt_gc_xmalloc_enabled() != 0 }
}

#[inline(always)]
pub fn gc_xcalloc_enabled() -> bool {
    unsafe { rb_usdt_gc_xcalloc_enabled() != 0 }
}

#[inline(always)]
pub fn gc_xfree_enabled() -> bool {
    unsafe { rb_usdt_gc_xfree_enabled() != 0 }
}

#[inline(always)]
pub fn gvl_acquire_enabled() -> bool {
    unsafe { rb_usdt_gvl_acquire_enabled() != 0 }
}

#[inline(always)]
pub fn gvl_release_enabled() -> bool {
    unsafe { rb_usdt_gvl_release_enabled() != 0 }
}

#[inline(always)]
pub fn rts_set_running_enabled() -> bool {
    unsafe { rb_usdt_rts_set_running_enabled() != 0 }
}

#[macro_export]
macro_rules! usdt_method_entry {
    ($classname:expr, $methodname:expr, $filename:expr, $lineno:expr) => {
        if $crate::usdt::method_entry_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$classname, |classname_ptr| {
                $crate::usdt::AsCStrPtr::with_c_str_ptr(&$methodname, |methodname_ptr| {
                    $crate::usdt::AsCStrPtr::with_c_str_ptr(&$filename, |filename_ptr| {
                        unsafe { $crate::usdt::rb_usdt_method_entry(classname_ptr, methodname_ptr, filename_ptr, $lineno as core::ffi::c_int); }
                    });
                });
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_method_return {
    ($classname:expr, $methodname:expr, $filename:expr, $lineno:expr) => {
        if $crate::usdt::method_return_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$classname, |classname_ptr| {
                $crate::usdt::AsCStrPtr::with_c_str_ptr(&$methodname, |methodname_ptr| {
                    $crate::usdt::AsCStrPtr::with_c_str_ptr(&$filename, |filename_ptr| {
                        unsafe { $crate::usdt::rb_usdt_method_return(classname_ptr, methodname_ptr, filename_ptr, $lineno as core::ffi::c_int); }
                    });
                });
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_cmethod_entry {
    ($classname:expr, $methodname:expr, $filename:expr, $lineno:expr) => {
        if $crate::usdt::cmethod_entry_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$classname, |classname_ptr| {
                $crate::usdt::AsCStrPtr::with_c_str_ptr(&$methodname, |methodname_ptr| {
                    $crate::usdt::AsCStrPtr::with_c_str_ptr(&$filename, |filename_ptr| {
                        unsafe { $crate::usdt::rb_usdt_cmethod_entry(classname_ptr, methodname_ptr, filename_ptr, $lineno as core::ffi::c_int); }
                    });
                });
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_cmethod_return {
    ($classname:expr, $methodname:expr, $filename:expr, $lineno:expr) => {
        if $crate::usdt::cmethod_return_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$classname, |classname_ptr| {
                $crate::usdt::AsCStrPtr::with_c_str_ptr(&$methodname, |methodname_ptr| {
                    $crate::usdt::AsCStrPtr::with_c_str_ptr(&$filename, |filename_ptr| {
                        unsafe { $crate::usdt::rb_usdt_cmethod_return(classname_ptr, methodname_ptr, filename_ptr, $lineno as core::ffi::c_int); }
                    });
                });
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_require_entry {
    ($rquiredfile:expr, $filename:expr, $lineno:expr) => {
        if $crate::usdt::require_entry_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$rquiredfile, |rquiredfile_ptr| {
                $crate::usdt::AsCStrPtr::with_c_str_ptr(&$filename, |filename_ptr| {
                    unsafe { $crate::usdt::rb_usdt_require_entry(rquiredfile_ptr, filename_ptr, $lineno as core::ffi::c_int); }
                });
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_require_return {
    ($requiredfile:expr, $filename:expr, $lineno:expr) => {
        if $crate::usdt::require_return_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$requiredfile, |requiredfile_ptr| {
                $crate::usdt::AsCStrPtr::with_c_str_ptr(&$filename, |filename_ptr| {
                    unsafe { $crate::usdt::rb_usdt_require_return(requiredfile_ptr, filename_ptr, $lineno as core::ffi::c_int); }
                });
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_find_require_entry {
    ($requiredfile:expr, $filename:expr, $lineno:expr) => {
        if $crate::usdt::find_require_entry_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$requiredfile, |requiredfile_ptr| {
                $crate::usdt::AsCStrPtr::with_c_str_ptr(&$filename, |filename_ptr| {
                    unsafe { $crate::usdt::rb_usdt_find_require_entry(requiredfile_ptr, filename_ptr, $lineno as core::ffi::c_int); }
                });
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_find_require_return {
    ($requiredfile:expr, $filename:expr, $lineno:expr) => {
        if $crate::usdt::find_require_return_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$requiredfile, |requiredfile_ptr| {
                $crate::usdt::AsCStrPtr::with_c_str_ptr(&$filename, |filename_ptr| {
                    unsafe { $crate::usdt::rb_usdt_find_require_return(requiredfile_ptr, filename_ptr, $lineno as core::ffi::c_int); }
                });
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_load_entry {
    ($loadedfile:expr, $filename:expr, $lineno:expr) => {
        if $crate::usdt::load_entry_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$loadedfile, |loadedfile_ptr| {
                $crate::usdt::AsCStrPtr::with_c_str_ptr(&$filename, |filename_ptr| {
                    unsafe { $crate::usdt::rb_usdt_load_entry(loadedfile_ptr, filename_ptr, $lineno as core::ffi::c_int); }
                });
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_load_return {
    ($loadedfile:expr, $filename:expr, $lineno:expr) => {
        if $crate::usdt::load_return_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$loadedfile, |loadedfile_ptr| {
                $crate::usdt::AsCStrPtr::with_c_str_ptr(&$filename, |filename_ptr| {
                    unsafe { $crate::usdt::rb_usdt_load_return(loadedfile_ptr, filename_ptr, $lineno as core::ffi::c_int); }
                });
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_raise {
    ($classname:expr, $filename:expr, $lineno:expr) => {
        if $crate::usdt::raise_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$classname, |classname_ptr| {
                $crate::usdt::AsCStrPtr::with_c_str_ptr(&$filename, |filename_ptr| {
                    unsafe { $crate::usdt::rb_usdt_raise(classname_ptr, filename_ptr, $lineno as core::ffi::c_int); }
                });
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_object_create {
    ($classname:expr, $filename:expr, $lineno:expr) => {
        if $crate::usdt::object_create_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$classname, |classname_ptr| {
                $crate::usdt::AsCStrPtr::with_c_str_ptr(&$filename, |filename_ptr| {
                    unsafe { $crate::usdt::rb_usdt_object_create(classname_ptr, filename_ptr, $lineno as core::ffi::c_int); }
                });
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_array_create {
    ($length:expr, $filename:expr, $lineno:expr) => {
        if $crate::usdt::array_create_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$filename, |filename_ptr| {
                unsafe { $crate::usdt::rb_usdt_array_create($length as core::ffi::c_long, filename_ptr, $lineno as core::ffi::c_int); }
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_hash_create {
    ($length:expr, $filename:expr, $lineno:expr) => {
        if $crate::usdt::hash_create_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$filename, |filename_ptr| {
                unsafe { $crate::usdt::rb_usdt_hash_create($length as core::ffi::c_long, filename_ptr, $lineno as core::ffi::c_int); }
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_string_create {
    ($length:expr, $filename:expr, $lineno:expr) => {
        if $crate::usdt::string_create_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$filename, |filename_ptr| {
                unsafe { $crate::usdt::rb_usdt_string_create($length as core::ffi::c_long, filename_ptr, $lineno as core::ffi::c_int); }
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_symbol_create {
    ($str:expr, $filename:expr, $lineno:expr) => {
        if $crate::usdt::symbol_create_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$str, |str_ptr| {
                $crate::usdt::AsCStrPtr::with_c_str_ptr(&$filename, |filename_ptr| {
                    unsafe { $crate::usdt::rb_usdt_symbol_create(str_ptr, filename_ptr, $lineno as core::ffi::c_int); }
                });
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_parse_begin {
    ($sourcefile:expr, $lineno:expr) => {
        if $crate::usdt::parse_begin_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$sourcefile, |sourcefile_ptr| {
                unsafe { $crate::usdt::rb_usdt_parse_begin(sourcefile_ptr, $lineno as core::ffi::c_int); }
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_parse_end {
    ($sourcefile:expr, $lineno:expr) => {
        if $crate::usdt::parse_end_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$sourcefile, |sourcefile_ptr| {
                unsafe { $crate::usdt::rb_usdt_parse_end(sourcefile_ptr, $lineno as core::ffi::c_int); }
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_insn {
    ($insns_name:expr) => {
        if $crate::usdt::insn_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$insns_name, |insns_name_ptr| {
                unsafe { $crate::usdt::rb_usdt_insn(insns_name_ptr); }
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_insn_operand {
    ($val:expr, $insns_name:expr) => {
        if $crate::usdt::insn_operand_enabled() {
            $crate::usdt::AsCStrPtr::with_c_str_ptr(&$val, |val_ptr| {
                $crate::usdt::AsCStrPtr::with_c_str_ptr(&$insns_name, |insns_name_ptr| {
                    unsafe { $crate::usdt::rb_usdt_insn_operand(val_ptr, insns_name_ptr); }
                });
            });
        }
    };
}

#[macro_export]
macro_rules! usdt_gc_mark_begin {
    () => {
        if $crate::usdt::gc_mark_begin_enabled() {
            unsafe { $crate::usdt::rb_usdt_gc_mark_begin(); }
        }
    };
}

#[macro_export]
macro_rules! usdt_gc_mark_end {
    () => {
        if $crate::usdt::gc_mark_end_enabled() {
            unsafe { $crate::usdt::rb_usdt_gc_mark_end(); }
        }
    };
}

#[macro_export]
macro_rules! usdt_gc_sweep_begin {
    () => {
        if $crate::usdt::gc_sweep_begin_enabled() {
            unsafe { $crate::usdt::rb_usdt_gc_sweep_begin(); }
        }
    };
}

#[macro_export]
macro_rules! usdt_gc_sweep_end {
    () => {
        if $crate::usdt::gc_sweep_end_enabled() {
            unsafe { $crate::usdt::rb_usdt_gc_sweep_end(); }
        }
    };
}

#[macro_export]
macro_rules! usdt_gc_enter {
    ($event:expr) => {
        if $crate::usdt::gc_enter_enabled() {
            unsafe { $crate::usdt::rb_usdt_gc_enter($event as core::ffi::c_int); }
        }
    };
}

#[macro_export]
macro_rules! usdt_gc_exit {
    ($event:expr) => {
        if $crate::usdt::gc_exit_enabled() {
            unsafe { $crate::usdt::rb_usdt_gc_exit($event as core::ffi::c_int); }
        }
    };
}

#[macro_export]
macro_rules! usdt_gc_mark_stacked_objects {
    ($popped_count:expr) => {
        if $crate::usdt::gc_mark_stacked_objects_enabled() {
            unsafe { $crate::usdt::rb_usdt_gc_mark_stacked_objects($popped_count as usize); }
        }
    };
}

#[macro_export]
macro_rules! usdt_gc_sweep_page {
    ($slot_size:expr, $final_slots:expr, $freed_slots:expr, $empty_slots:expr) => {
        if $crate::usdt::gc_sweep_page_enabled() {
            unsafe { $crate::usdt::rb_usdt_gc_sweep_page($slot_size as core::ffi::c_int, $final_slots as core::ffi::c_int, $freed_slots as core::ffi::c_int, $empty_slots as core::ffi::c_int); }
        }
    };
}

#[macro_export]
macro_rules! usdt_gc_obj_new {
    ($obj:expr, $flags:expr) => {
        if $crate::usdt::gc_obj_new_enabled() {
            unsafe { $crate::usdt::rb_usdt_gc_obj_new($obj as *const core::ffi::c_void, $flags as usize); }
        }
    };
}

#[macro_export]
macro_rules! usdt_gc_obj_free {
    ($obj:expr, $flags:expr) => {
        if $crate::usdt::gc_obj_free_enabled() {
            unsafe { $crate::usdt::rb_usdt_gc_obj_free($obj as *const core::ffi::c_void, $flags as usize); }
        }
    };
}

#[macro_export]
macro_rules! usdt_gc_xmalloc {
    ($n:expr, $size:expr) => {
        if $crate::usdt::gc_xmalloc_enabled() {
            unsafe { $crate::usdt::rb_usdt_gc_xmalloc($n as usize, $size as usize); }
        }
    };
}

#[macro_export]
macro_rules! usdt_gc_xcalloc {
    ($n:expr, $size:expr) => {
        if $crate::usdt::gc_xcalloc_enabled() {
            unsafe { $crate::usdt::rb_usdt_gc_xcalloc($n as usize, $size as usize); }
        }
    };
}

#[macro_export]
macro_rules! usdt_gc_xfree {
    ($obj:expr, $size:expr) => {
        if $crate::usdt::gc_xfree_enabled() {
            unsafe { $crate::usdt::rb_usdt_gc_xfree($obj as *const core::ffi::c_void, $size as usize); }
        }
    };
}

#[macro_export]
macro_rules! usdt_gvl_acquire {
    () => {
        if $crate::usdt::gvl_acquire_enabled() {
            unsafe { $crate::usdt::rb_usdt_gvl_acquire(); }
        }
    };
}

#[macro_export]
macro_rules! usdt_gvl_release {
    () => {
        if $crate::usdt::gvl_release_enabled() {
            unsafe { $crate::usdt::rb_usdt_gvl_release(); }
        }
    };
}

#[macro_export]
macro_rules! usdt_rts_set_running {
    ($sched:expr, $old_thread:expr, $new_thread:expr) => {
        if $crate::usdt::rts_set_running_enabled() {
            unsafe { $crate::usdt::rb_usdt_rts_set_running($sched as *const core::ffi::c_void, $old_thread as *const core::ffi::c_void, $new_thread as *const core::ffi::c_void); }
        }
    };
}

pub use crate::usdt_method_entry as method_entry;
pub use crate::usdt_method_return as method_return;
pub use crate::usdt_cmethod_entry as cmethod_entry;
pub use crate::usdt_cmethod_return as cmethod_return;
pub use crate::usdt_require_entry as require_entry;
pub use crate::usdt_require_return as require_return;
pub use crate::usdt_find_require_entry as find_require_entry;
pub use crate::usdt_find_require_return as find_require_return;
pub use crate::usdt_load_entry as load_entry;
pub use crate::usdt_load_return as load_return;
pub use crate::usdt_raise as raise;
pub use crate::usdt_object_create as object_create;
pub use crate::usdt_array_create as array_create;
pub use crate::usdt_hash_create as hash_create;
pub use crate::usdt_string_create as string_create;
pub use crate::usdt_symbol_create as symbol_create;
pub use crate::usdt_parse_begin as parse_begin;
pub use crate::usdt_parse_end as parse_end;
pub use crate::usdt_insn as insn;
pub use crate::usdt_insn_operand as insn_operand;
pub use crate::usdt_gc_mark_begin as gc_mark_begin;
pub use crate::usdt_gc_mark_end as gc_mark_end;
pub use crate::usdt_gc_sweep_begin as gc_sweep_begin;
pub use crate::usdt_gc_sweep_end as gc_sweep_end;
pub use crate::usdt_gc_enter as gc_enter;
pub use crate::usdt_gc_exit as gc_exit;
pub use crate::usdt_gc_mark_stacked_objects as gc_mark_stacked_objects;
pub use crate::usdt_gc_sweep_page as gc_sweep_page;
pub use crate::usdt_gc_obj_new as gc_obj_new;
pub use crate::usdt_gc_obj_free as gc_obj_free;
pub use crate::usdt_gc_xmalloc as gc_xmalloc;
pub use crate::usdt_gc_xcalloc as gc_xcalloc;
pub use crate::usdt_gc_xfree as gc_xfree;
pub use crate::usdt_gvl_acquire as gvl_acquire;
pub use crate::usdt_gvl_release as gvl_release;
pub use crate::usdt_rts_set_running as rts_set_running;
