[package]
name = "zjit"
version = "0.0.1"
edition = "2024"
rust-version = "1.85.0" # Minimally supported rust version
publish = false         # Don't publish to crates.io

[dependencies]
# No required dependencies to simplify build process.
jit = { version = "0.1.0", path = "../jit" }

[dev-dependencies]
yjit = { path = "../yjit" }

# NOTE: Development builds select a set of these via configure.ac
# For debugging, `make V=1` shows exact cargo invocation.
[features]
disasm = []
runtime_checks = []
stats_allocator = []
