#!/usr/bin/env ruby
# frozen_string_literal: true

# tool/gen_usdt_bindings.rb
# Build-time generator script that parses probes.d and outputs:
#   - C probe bridge header (probes_bridge.h)
#   - C probe bridge implementation (probes_bridge.c)
#   - Rust USDT bindings module (core_rs/src/usdt.rs)

require 'optparse'
require 'fileutils'

options = {
  probes_d: File.expand_path('../probes.d', __dir__),
  c_header: File.expand_path('../probes_bridge.h', __dir__),
  c_impl: File.expand_path('../probes_bridge.c', __dir__),
  rust_file: File.expand_path('../core_rs/src/usdt.rs', __dir__)
}

OptionParser.new do |opts|
  opts.banner = "Usage: gen_usdt_bindings.rb [options]"
  opts.on("--probes-d PATH", "Path to probes.d") { |v| options[:probes_d] = File.expand_path(v) }
  opts.on("--c-header PATH", "Path to generated probes_bridge.h") { |v| options[:c_header] = File.expand_path(v) }
  opts.on("--c-impl PATH", "Path to generated probes_bridge.c") { |v| options[:c_impl] = File.expand_path(v) }
  opts.on("--rust-file PATH", "Path to generated core_rs/src/usdt.rs") { |v| options[:rust_file] = File.expand_path(v) }
end.parse!

unless File.exist?(options[:probes_d])
  puts "Error: #{options[:probes_d]} does not exist."
  exit 1
end

content = File.read(options[:probes_d])

# 1. Parse probes.d
def parse_probes(content)
  text = content.gsub(%r'/\*.*?\*/'m, '')
  text.gsub!(/^#(?:pragma|include).*\n/, '')

  provider_body = if text =~ /provider\s+ruby\s*\{(.*?)\};/m
                    $1
                  else
                    text
                  end

  probes = []

  provider_body.each_line do |line|
    line = line.strip
    next if line.empty?
    next if line.start_with?('#') # ignore preprocessor directives

    if line =~ /^probe\s+([a-zA-Z0-9_]+)\s*\((.*?)\)\s*;/
      raw_name = $1
      raw_args = $2.strip

      c_func_name = raw_name.gsub(/__/, '_')
      c_macro_name = raw_name.upcase.gsub(/__/, '_')

      parsed_args = []
      unless raw_args.empty? || raw_args == 'void'
        raw_args.split(',').each do |arg_str|
          arg_str = arg_str.strip
          if arg_str =~ /^(.*?)\s*([*\w]+)$/
            type_part = $1.strip
            name_part = $2.strip
            if name_part.start_with?('*')
              type_part = "#{type_part} *"
              name_part = name_part[1..-1].strip
            end
            parsed_args << { type: type_part, name: name_part }
          else
            raise "Cannot parse probe arg: #{arg_str}"
          end
        end
      end

      probes << {
        raw_name: raw_name,
        c_func_name: c_func_name,
        c_macro_name: c_macro_name,
        args: parsed_args
      }
    end
  end

  probes
end

probes = parse_probes(content)

def c_type_to_rust_ffi(c_type)
  case c_type
  when 'const char *'
    '*const core::ffi::c_char'
  when 'int'
    'core::ffi::c_int'
  when 'long'
    'core::ffi::c_long'
  when 'size_t', 'uintptr_t'
    'usize'
  when 'void *'
    '*const core::ffi::c_void'
  else
    raise "Unknown C type for Rust FFI: #{c_type}"
  end
end

def rust_cast_expr(var_expr, c_type)
  case c_type
  when 'int'
    "#{var_expr} as core::ffi::c_int"
  when 'long'
    "#{var_expr} as core::ffi::c_long"
  when 'size_t', 'uintptr_t'
    "#{var_expr} as usize"
  when 'void *'
    "#{var_expr} as *const core::ffi::c_void"
  else
    var_expr
  end
end

# 2. Generate probes_bridge.h
c_header_content = []
c_header_content << "/* Auto-generated by tool/gen_usdt_bindings.rb. Do not edit. */"
c_header_content << "#ifndef RUBY_PROBES_BRIDGE_H"
c_header_content << "#define RUBY_PROBES_BRIDGE_H"
c_header_content << ""
c_header_content << "#include <stddef.h>"
c_header_content << "#include <stdint.h>"
c_header_content << "#include \"ruby/internal/attr/noinline.h\""
c_header_content << "#include \"ruby/internal/dllexport.h\""
c_header_content << ""
c_header_content << "RBIMPL_SYMBOL_EXPORT_BEGIN()"
c_header_content << ""

probes.each do |p|
  c_args = p[:args].map { |a| "#{a[:type]} #{a[:name]}" }.join(", ")
  c_args = "void" if c_args.empty?
  c_header_content << "int rb_usdt_#{p[:c_func_name]}_enabled(void);"
  c_header_content << "void rb_usdt_#{p[:c_func_name]}(#{c_args});"
  c_header_content << ""
end

c_header_content << "RBIMPL_SYMBOL_EXPORT_END()"
c_header_content << ""
c_header_content << "#endif /* RUBY_PROBES_BRIDGE_H */"
c_header_content << ""

# 3. Generate probes_bridge.c
c_impl_content = []
c_impl_content << "/* Auto-generated by tool/gen_usdt_bindings.rb. Do not edit. */"
c_impl_content << "#include \"probes.h\""
c_impl_content << "#include \"probes_bridge.h\""
c_impl_content << ""
c_impl_content << "RBIMPL_SYMBOL_EXPORT_BEGIN()"
c_impl_content << ""

probes.each do |p|
  c_args = p[:args].map { |a| "#{a[:type]} #{a[:name]}" }.join(", ")
  c_args = "void" if c_args.empty?
  call_args = p[:args].map { |a| a[:name] }.join(", ")

  c_impl_content << "int rb_usdt_#{p[:c_func_name]}_enabled(void) {"
  c_impl_content << "#ifdef RUBY_DTRACE_#{p[:c_macro_name]}_ENABLED"
  c_impl_content << "    return RUBY_DTRACE_#{p[:c_macro_name]}_ENABLED();"
  c_impl_content << "#else"
  c_impl_content << "    return 0;"
  c_impl_content << "#endif"
  c_impl_content << "}"
  c_impl_content << ""

  c_impl_content << "void rb_usdt_#{p[:c_func_name]}(#{c_args}) {"
  c_impl_content << "#ifdef RUBY_DTRACE_#{p[:c_macro_name]}"
  c_impl_content << "    RUBY_DTRACE_#{p[:c_macro_name]}(#{call_args});"
  c_impl_content << "#endif"
  c_impl_content << "}"
  c_impl_content << ""
end

c_impl_content << "RBIMPL_SYMBOL_EXPORT_END()"
c_impl_content << ""

# 4. Generate core_rs/src/usdt.rs
rust_content = []
rust_content << "/* Auto-generated by tool/gen_usdt_bindings.rb. Do not edit. */"
rust_content << "//! Rust USDT probe bindings for core_rs"
rust_content << "//! Provides zero-cost, type-safe Rust abstractions for USDT dynamic tracing."
rust_content << ""

rust_content << "pub trait AsCStrPtr {"
rust_content << "    fn with_c_str_ptr<R, F: FnOnce(*const core::ffi::c_char) -> R>(&self, f: F) -> R;"
rust_content << "}"
rust_content << ""
rust_content << "impl AsCStrPtr for *const core::ffi::c_char {"
rust_content << "    #[inline(always)]"
rust_content << "    fn with_c_str_ptr<R, F: FnOnce(*const core::ffi::c_char) -> R>(&self, f: F) -> R {"
rust_content << "        f(*self)"
rust_content << "    }"
rust_content << "}"
rust_content << ""
rust_content << "impl AsCStrPtr for *mut core::ffi::c_char {"
rust_content << "    #[inline(always)]"
rust_content << "    fn with_c_str_ptr<R, F: FnOnce(*const core::ffi::c_char) -> R>(&self, f: F) -> R {"
rust_content << "        f(*self as *const core::ffi::c_char)"
rust_content << "    }"
rust_content << "}"
rust_content << ""
rust_content << "impl AsCStrPtr for &core::ffi::CStr {"
rust_content << "    #[inline(always)]"
rust_content << "    fn with_c_str_ptr<R, F: FnOnce(*const core::ffi::c_char) -> R>(&self, f: F) -> R {"
rust_content << "        f(self.as_ptr())"
rust_content << "    }"
rust_content << "}"
rust_content << ""
rust_content << "impl AsCStrPtr for &str {"
rust_content << "    #[inline(always)]"
rust_content << "    fn with_c_str_ptr<R, F: FnOnce(*const core::ffi::c_char) -> R>(&self, f: F) -> R {"
rust_content << "        let bytes = self.as_bytes();"
rust_content << "        if !bytes.is_empty() && bytes[bytes.len() - 1] == 0 {"
rust_content << "            f(bytes.as_ptr() as *const core::ffi::c_char)"
rust_content << "        } else {"
rust_content << "            let mut buf = [0u8; 256];"
rust_content << "            let len = bytes.len().min(255);"
rust_content << "            buf[..len].copy_from_slice(&bytes[..len]);"
rust_content << "            buf[len] = 0;"
rust_content << "            f(buf.as_ptr() as *const core::ffi::c_char)"
rust_content << "        }"
rust_content << "    }"
rust_content << "}"
rust_content << ""
rust_content << "impl AsCStrPtr for &[u8] {"
rust_content << "    #[inline(always)]"
rust_content << "    fn with_c_str_ptr<R, F: FnOnce(*const core::ffi::c_char) -> R>(&self, f: F) -> R {"
rust_content << "        if !self.is_empty() && self[self.len() - 1] == 0 {"
rust_content << "            f(self.as_ptr() as *const core::ffi::c_char)"
rust_content << "        } else {"
rust_content << "            let mut buf = [0u8; 256];"
rust_content << "            let len = self.len().min(255);"
rust_content << "            buf[..len].copy_from_slice(&self[..len]);"
rust_content << "            buf[len] = 0;"
rust_content << "            f(buf.as_ptr() as *const core::ffi::c_char)"
rust_content << "        }"
rust_content << "    }"
rust_content << "}"
rust_content << ""

rust_content << "unsafe extern \"C\" {"
probes.each do |p|
  rust_args = p[:args].map { |a| "#{a[:name]}: #{c_type_to_rust_ffi(a[:type])}" }.join(", ")
  rust_content << "    pub fn rb_usdt_#{p[:c_func_name]}_enabled() -> core::ffi::c_int;"
  rust_content << "    pub fn rb_usdt_#{p[:c_func_name]}(#{rust_args});"
end
rust_content << "}"
rust_content << ""

probes.each do |p|
  rust_content << "#[inline(always)]"
  rust_content << "pub fn #{p[:c_func_name]}_enabled() -> bool {"
  rust_content << "    unsafe { rb_usdt_#{p[:c_func_name]}_enabled() != 0 }"
  rust_content << "}"
  rust_content << ""
end

def emit_str_wrappers(str_args, all_args, c_func_name)
  if str_args.empty?
    call_exprs = all_args.map do |a|
      if a[:type] == 'const char *'
        "#{a[:name]}_ptr"
      else
        rust_cast_expr("$#{a[:name]}", a[:type])
      end
    end.join(", ")
    indent = "    " * (3 + all_args.count { |a| a[:type] == 'const char *' })
    "#{indent}unsafe { $crate::usdt::rb_usdt_#{c_func_name}(#{call_exprs}); }"
  else
    head = str_args.first
    tail = str_args[1..-1]
    indent = "    " * (3 + (all_args.count { |a| a[:type] == 'const char *' } - str_args.count))
    res = "#{indent}$crate::usdt::AsCStrPtr::with_c_str_ptr(&$#{head[:name]}, |#{head[:name]}_ptr| {\n"
    res += emit_str_wrappers(tail, all_args, c_func_name)
    res += "\n#{indent}});"
    res
  end
end

probes.each do |p|
  macro_args = p[:args].map { |a| "$#{a[:name]}:expr" }.join(", ")
  macro_name = "usdt_#{p[:c_func_name]}"

  rust_content << "#[macro_export]"
  rust_content << "macro_rules! #{macro_name} {"
  rust_content << "    (#{macro_args}) => {"
  rust_content << "        if $crate::usdt::#{p[:c_func_name]}_enabled() {"

  str_args = p[:args].select { |a| a[:type] == 'const char *' }
  rust_content << emit_str_wrappers(str_args, p[:args], p[:c_func_name])
  rust_content << "        }"
  rust_content << "    };"
  rust_content << "}"
  rust_content << ""
end

# Re-exports inside usdt module
probes.each do |p|
  rust_content << "pub use crate::usdt_#{p[:c_func_name]} as #{p[:c_func_name]};"
end
rust_content << ""

# Write files
FileUtils.mkdir_p(File.dirname(options[:c_header]))
FileUtils.mkdir_p(File.dirname(options[:c_impl]))
FileUtils.mkdir_p(File.dirname(options[:rust_file]))

File.write(options[:c_header], c_header_content.join("\n"))
File.write(options[:c_impl], c_impl_content.join("\n"))
File.write(options[:rust_file], rust_content.join("\n"))

puts "Successfully generated:"
puts "  #{options[:c_header]}"
puts "  #{options[:c_impl]}"
puts "  #{options[:rust_file]}"
