#!/usr/bin/env python3
"""
Update and verify the C-to-Rust porting ledger (PORTING.md).

Parses inline @porting-status annotations in C source (*.c) and header (*.h) files
and maintains the root PORTING.md ledger file.
"""

import sys
import os
import re
import argparse
from pathlib import Path

STATUS_REGEX = re.compile(
    r'@porting-status:\s*([a-zA-Z0-9_\-]+)(?:\s*-\s*(.*?))?\s*(?:\*/|\r?\n|$)',
    re.MULTILINE
)

EXCLUDE_DIRS = {
    ".git", ".github", "tmp", "build", "autom4te.cache", "node_modules", "target", "spec"
}

def scan_c_files(root_dir):
    """Scan root_dir for C source (*.c) and header (*.h) files and extract @porting-status annotations."""
    records = []

    for dirpath, dirnames, filenames in os.walk(root_dir):
        # Filter out excluded directories
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIRS]

        for filename in sorted(filenames):
            if filename.endswith(".c") or filename.endswith(".h"):
                file_path = Path(dirpath) / filename
                rel_path = file_path.relative_to(root_dir).as_posix()

                try:
                    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                        content = f.read()
                except Exception as e:
                    print(f"Warning: Unable to read {rel_path}: {e}", file=sys.stderr)
                    continue

                match = STATUS_REGEX.search(content)
                if match:
                    status = match.group(1).lower()
                    notes = match.group(2).strip() if match.group(2) else ""
                    records.append({
                        "file": rel_path,
                        "status": status,
                        "notes": notes,
                        "has_tag": True
                    })

    # Sort records alphabetically by relative file path
    records.sort(key=lambda x: x["file"])
    return records

def generate_ledger_markdown(records):
    """Generate markdown content for PORTING.md based on scanned records."""
    total_files = len(records)
    status_counts = {}
    for r in records:
        st = r["status"]
        status_counts[st] = status_counts.get(st, 0) + 1

    ported = status_counts.get("ported", 0)
    in_progress = status_counts.get("in-progress", 0) + status_counts.get("in_progress", 0)
    unported = status_counts.get("unported", 0)
    blocked = status_counts.get("blocked", 0)
    not_planned = status_counts.get("not-planned", 0) + status_counts.get("not_planned", 0)

    lines = []
    lines.append("# C-to-Rust Porting Ledger")
    lines.append("")
    lines.append("*This ledger is automatically generated by `python3 tool/update_porting_ledger.py`. Do not edit manually.*")
    lines.append("")
    lines.append("## Migration Summary")
    lines.append("")
    lines.append(f"- **Total Tracked Files:** {total_files}")
    lines.append(f"- **Ported:** {ported}")
    lines.append(f"- **In Progress:** {in_progress}")
    lines.append(f"- **Unported:** {unported}")
    if blocked > 0:
        lines.append(f"- **Blocked:** {blocked}")
    if not_planned > 0:
        lines.append(f"- **Not Planned:** {not_planned}")
    lines.append("")
    lines.append("## File Status Details")
    lines.append("")
    lines.append("| File | Status | Notes |")
    lines.append("| --- | --- | --- |")

    for r in records:
        f_str = f"`{r['file']}`"
        s_str = r["status"]
        n_str = r["notes"]
        lines.append(f"| {f_str} | {s_str} | {n_str} |")

    lines.append("")
    return "\n".join(lines)

def main():
    repo_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description="Maintain C-to-Rust porting ledger.")
    parser.add_argument("--verify", action="store_true", help="Verify if PORTING.md is up to date without writing.")
    parser.add_argument("--root", type=str, default=str(repo_root), help="Root directory of repository.")
    parser.add_argument("--output", type=str, default="PORTING.md", help="Output ledger file path.")

    args = parser.parse_args()

    root_dir = Path(args.root).resolve()
    output_path = root_dir / args.output if not Path(args.output).is_absolute() else Path(args.output)

    records = scan_c_files(root_dir)
    generated_content = generate_ledger_markdown(records)

    if args.verify:
        if not output_path.exists():
            print(f"Error: {output_path.name} does not exist. Run 'python3 tool/update_porting_ledger.py' to generate it.", file=sys.stderr)
            sys.exit(1)

        try:
            with open(output_path, "r", encoding="utf-8") as f:
                existing_content = f.read()
        except Exception as e:
            print(f"Error reading {output_path.name}: {e}", file=sys.stderr)
            sys.exit(1)

        if existing_content.strip() == generated_content.strip():
            print(f"Verification successful: {output_path.name} is up to date.")
            sys.exit(0)
        else:
            print(f"Error: {output_path.name} is out of date. Please run 'python3 tool/update_porting_ledger.py' to update.", file=sys.stderr)
            sys.exit(1)
    else:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(generated_content)
        print(f"Successfully generated {output_path.name} with {len(records)} tracked C files.")

if __name__ == "__main__":
    main()
