/* automatically generated by rust-bindgen 0.70.1 */

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val {
            *byte |= mask;
        } else {
            *byte &= !mask;
        }
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
}
#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::std::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::std::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        ::std::slice::from_raw_parts(self.as_ptr(), len)
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        ::std::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
    }
}
impl<T> ::std::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
#[repr(C)]
pub struct __BindgenUnionField<T>(::std::marker::PhantomData<T>);
impl<T> __BindgenUnionField<T> {
    #[inline]
    pub const fn new() -> Self {
        __BindgenUnionField(::std::marker::PhantomData)
    }
    #[inline]
    pub unsafe fn as_ref(&self) -> &T {
        ::std::mem::transmute(self)
    }
    #[inline]
    pub unsafe fn as_mut(&mut self) -> &mut T {
        ::std::mem::transmute(self)
    }
}
impl<T> ::std::default::Default for __BindgenUnionField<T> {
    #[inline]
    fn default() -> Self {
        Self::new()
    }
}
impl<T> ::std::clone::Clone for __BindgenUnionField<T> {
    #[inline]
    fn clone(&self) -> Self {
        *self
    }
}
impl<T> ::std::marker::Copy for __BindgenUnionField<T> {}
impl<T> ::std::fmt::Debug for __BindgenUnionField<T> {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        fmt.write_str("__BindgenUnionField")
    }
}
impl<T> ::std::hash::Hash for __BindgenUnionField<T> {
    fn hash<H: ::std::hash::Hasher>(&self, _state: &mut H) {}
}
impl<T> ::std::cmp::PartialEq for __BindgenUnionField<T> {
    fn eq(&self, _other: &__BindgenUnionField<T>) -> bool {
        true
    }
}
impl<T> ::std::cmp::Eq for __BindgenUnionField<T> {}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __sigset_t {
    pub __val: [::std::os::raw::c_ulong; 16usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union __atomic_wide_counter {
    pub __value64: ::std::os::raw::c_ulonglong,
    pub __value32: __atomic_wide_counter__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __atomic_wide_counter__bindgen_ty_1 {
    pub __low: ::std::os::raw::c_uint,
    pub __high: ::std::os::raw::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __pthread_internal_list {
    pub __prev: *mut __pthread_internal_list,
    pub __next: *mut __pthread_internal_list,
}
pub type __pthread_list_t = __pthread_internal_list;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __pthread_mutex_s {
    pub __lock: ::std::os::raw::c_int,
    pub __count: ::std::os::raw::c_uint,
    pub __owner: ::std::os::raw::c_int,
    pub __nusers: ::std::os::raw::c_uint,
    pub __kind: ::std::os::raw::c_int,
    pub __spins: ::std::os::raw::c_short,
    pub __elision: ::std::os::raw::c_short,
    pub __list: __pthread_list_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct __pthread_cond_s {
    pub __wseq: __atomic_wide_counter,
    pub __g1_start: __atomic_wide_counter,
    pub __g_refs: [::std::os::raw::c_uint; 2usize],
    pub __g_size: [::std::os::raw::c_uint; 2usize],
    pub __g1_orig_size: ::std::os::raw::c_uint,
    pub __wrefs: ::std::os::raw::c_uint,
    pub __g_signals: [::std::os::raw::c_uint; 2usize],
}
pub type pthread_t = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_mutex_t {
    pub __data: __pthread_mutex_s,
    pub __size: [::std::os::raw::c_char; 40usize],
    pub __align: ::std::os::raw::c_long,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_cond_t {
    pub __data: __pthread_cond_s,
    pub __size: [::std::os::raw::c_char; 48usize],
    pub __align: ::std::os::raw::c_longlong,
}
pub type ID = ::std::os::raw::c_ulong;
pub const RUBY_Qfalse: ruby_special_consts = 0;
pub const RUBY_Qnil: ruby_special_consts = 4;
pub const RUBY_Qtrue: ruby_special_consts = 20;
pub const RUBY_Qundef: ruby_special_consts = 36;
pub const RUBY_IMMEDIATE_MASK: ruby_special_consts = 7;
pub const RUBY_FIXNUM_FLAG: ruby_special_consts = 1;
pub const RUBY_FLONUM_MASK: ruby_special_consts = 3;
pub const RUBY_FLONUM_FLAG: ruby_special_consts = 2;
pub const RUBY_SYMBOL_FLAG: ruby_special_consts = 12;
pub const RUBY_SPECIAL_SHIFT: ruby_special_consts = 8;
pub type ruby_special_consts = u32;
#[repr(C)]
pub struct RBasic {
    pub flags: VALUE,
    pub klass: VALUE,
}
pub const RUBY_T_NONE: ruby_value_type = 0;
pub const RUBY_T_OBJECT: ruby_value_type = 1;
pub const RUBY_T_CLASS: ruby_value_type = 2;
pub const RUBY_T_MODULE: ruby_value_type = 3;
pub const RUBY_T_FLOAT: ruby_value_type = 4;
pub const RUBY_T_STRING: ruby_value_type = 5;
pub const RUBY_T_REGEXP: ruby_value_type = 6;
pub const RUBY_T_ARRAY: ruby_value_type = 7;
pub const RUBY_T_HASH: ruby_value_type = 8;
pub const RUBY_T_STRUCT: ruby_value_type = 9;
pub const RUBY_T_BIGNUM: ruby_value_type = 10;
pub const RUBY_T_FILE: ruby_value_type = 11;
pub const RUBY_T_DATA: ruby_value_type = 12;
pub const RUBY_T_MATCH: ruby_value_type = 13;
pub const RUBY_T_COMPLEX: ruby_value_type = 14;
pub const RUBY_T_RATIONAL: ruby_value_type = 15;
pub const RUBY_T_NIL: ruby_value_type = 17;
pub const RUBY_T_TRUE: ruby_value_type = 18;
pub const RUBY_T_FALSE: ruby_value_type = 19;
pub const RUBY_T_SYMBOL: ruby_value_type = 20;
pub const RUBY_T_FIXNUM: ruby_value_type = 21;
pub const RUBY_T_UNDEF: ruby_value_type = 22;
pub const RUBY_T_IMEMO: ruby_value_type = 26;
pub const RUBY_T_NODE: ruby_value_type = 27;
pub const RUBY_T_ICLASS: ruby_value_type = 28;
pub const RUBY_T_ZOMBIE: ruby_value_type = 29;
pub const RUBY_T_MOVED: ruby_value_type = 30;
pub const RUBY_T_MASK: ruby_value_type = 31;
pub type ruby_value_type = u32;
pub const RUBY_FL_USHIFT: ruby_fl_ushift = 12;
pub type ruby_fl_ushift = u32;
pub const RUBY_FL_WB_PROTECTED: ruby_fl_type = 32;
pub const RUBY_FL_PROMOTED: ruby_fl_type = 32;
pub const RUBY_FL_UNUSED6: ruby_fl_type = 64;
pub const RUBY_FL_FINALIZE: ruby_fl_type = 128;
pub const RUBY_FL_EXIVAR: ruby_fl_type = 0;
pub const RUBY_FL_SHAREABLE: ruby_fl_type = 256;
pub const RUBY_FL_WEAK_REFERENCE: ruby_fl_type = 512;
pub const RUBY_FL_UNUSED10: ruby_fl_type = 1024;
pub const RUBY_FL_FREEZE: ruby_fl_type = 2048;
pub const RUBY_FL_USER0: ruby_fl_type = 4096;
pub const RUBY_FL_USER1: ruby_fl_type = 8192;
pub const RUBY_FL_USER2: ruby_fl_type = 16384;
pub const RUBY_FL_USER3: ruby_fl_type = 32768;
pub const RUBY_FL_USER4: ruby_fl_type = 65536;
pub const RUBY_FL_USER5: ruby_fl_type = 131072;
pub const RUBY_FL_USER6: ruby_fl_type = 262144;
pub const RUBY_FL_USER7: ruby_fl_type = 524288;
pub const RUBY_FL_USER8: ruby_fl_type = 1048576;
pub const RUBY_FL_USER9: ruby_fl_type = 2097152;
pub const RUBY_FL_USER10: ruby_fl_type = 4194304;
pub const RUBY_FL_USER11: ruby_fl_type = 8388608;
pub const RUBY_FL_USER12: ruby_fl_type = 16777216;
pub const RUBY_FL_USER13: ruby_fl_type = 33554432;
pub const RUBY_FL_USER14: ruby_fl_type = 67108864;
pub const RUBY_FL_USER15: ruby_fl_type = 134217728;
pub const RUBY_FL_USER16: ruby_fl_type = 268435456;
pub const RUBY_FL_USER17: ruby_fl_type = 536870912;
pub const RUBY_FL_USER18: ruby_fl_type = 1073741824;
pub const RUBY_FL_USER19: ruby_fl_type = -2147483648;
pub const RUBY_ELTS_SHARED: ruby_fl_type = 4096;
pub const RUBY_FL_SINGLETON: ruby_fl_type = 8192;
pub type ruby_fl_type = i32;
pub const RSTRING_NOEMBED: ruby_rstring_flags = 8192;
pub const RSTRING_FSTR: ruby_rstring_flags = 536870912;
pub type ruby_rstring_flags = u32;
pub type st_data_t = ::std::os::raw::c_ulong;
pub type st_index_t = st_data_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_hash_type {
    pub compare: ::std::option::Option<
        unsafe extern "C" fn(arg1: st_data_t, arg2: st_data_t) -> ::std::os::raw::c_int,
    >,
    pub hash: ::std::option::Option<unsafe extern "C" fn(arg1: st_data_t) -> st_index_t>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_table_entry {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_table {
    pub entry_power: ::std::os::raw::c_uchar,
    pub bin_power: ::std::os::raw::c_uchar,
    pub size_ind: ::std::os::raw::c_uchar,
    pub rebuilds_num: ::std::os::raw::c_uchar,
    pub entries_start: ::std::os::raw::c_uint,
    pub type_: *const st_hash_type,
    pub num_entries: st_index_t,
    pub entries_bound: st_index_t,
    pub entries: *mut st_table_entry,
}
pub const ST_CONTINUE: st_retval = 0;
pub const ST_STOP: st_retval = 1;
pub const ST_DELETE: st_retval = 2;
pub const ST_CHECK: st_retval = 3;
pub const ST_REPLACE: st_retval = 4;
pub type st_retval = u32;
pub const RARRAY_EMBED_FLAG: ruby_rarray_flags = 8192;
pub const RARRAY_EMBED_LEN_MASK: ruby_rarray_flags = 4161536;
pub type ruby_rarray_flags = u32;
pub const RARRAY_EMBED_LEN_SHIFT: ruby_rarray_consts = 15;
pub type ruby_rarray_consts = u32;
#[repr(C)]
pub struct RArray {
    pub basic: RBasic,
    pub as_: RArray__bindgen_ty_1,
}
#[repr(C)]
pub struct RArray__bindgen_ty_1 {
    pub heap: __BindgenUnionField<RArray__bindgen_ty_1__bindgen_ty_1>,
    pub ary: __BindgenUnionField<[VALUE; 1usize]>,
    pub bindgen_union_field: [u64; 3usize],
}
#[repr(C)]
pub struct RArray__bindgen_ty_1__bindgen_ty_1 {
    pub len: ::std::os::raw::c_long,
    pub aux: RArray__bindgen_ty_1__bindgen_ty_1__bindgen_ty_1,
    pub ptr: *const VALUE,
}
#[repr(C)]
pub struct RArray__bindgen_ty_1__bindgen_ty_1__bindgen_ty_1 {
    pub capa: __BindgenUnionField<::std::os::raw::c_long>,
    pub shared_root: __BindgenUnionField<VALUE>,
    pub bindgen_union_field: u64,
}
pub const RMODULE_IS_REFINEMENT: ruby_rmodule_flags = 8192;
pub type ruby_rmodule_flags = u32;
pub type rb_event_flag_t = u32;
pub type rb_unblock_function_t =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>;
pub type rb_atomic_t = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_id_table {
    pub capa: ::std::os::raw::c_int,
    pub num: ::std::os::raw::c_int,
    pub used: ::std::os::raw::c_int,
    pub buf: *mut ::std::os::raw::c_void,
}
pub type attr_index_t = u8;
pub type shape_id_t = u32;
pub type __jmp_buf = [::std::os::raw::c_long; 8usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __jmp_buf_tag {
    pub __jmpbuf: __jmp_buf,
    pub __mask_was_saved: ::std::os::raw::c_int,
    pub __saved_mask: __sigset_t,
}
pub type jmp_buf = [__jmp_buf_tag; 1usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ccan_list_node {
    pub next: *mut ccan_list_node,
    pub prev: *mut ccan_list_node,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ccan_list_head {
    pub n: ccan_list_node,
}
#[repr(C)]
pub struct rb_box_struct {
    pub box_object: VALUE,
    pub box_id: ::std::os::raw::c_long,
    pub top_self: VALUE,
    pub load_path: VALUE,
    pub load_path_snapshot: VALUE,
    pub load_path_check_cache: VALUE,
    pub expanded_load_path: VALUE,
    pub expanded_load_path_maxlen: ::std::os::raw::c_long,
    pub loaded_features: VALUE,
    pub loaded_features_snapshot: VALUE,
    pub loaded_features_realpaths: VALUE,
    pub loaded_features_realpath_map: VALUE,
    pub loaded_features_index: *mut st_table,
    pub loading_table: *mut st_table,
    pub ruby_dln_libmap: VALUE,
    pub gvar_tbl: VALUE,
    pub classext_cow_classes: *mut st_table,
    pub is_root: bool,
    pub is_user: bool,
    pub is_optional: bool,
}
pub type rb_box_t = rb_box_struct;
pub type rb_serial_t = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct set_table_entry {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct set_table {
    pub entry_power: ::std::os::raw::c_uchar,
    pub bin_power: ::std::os::raw::c_uchar,
    pub size_ind: ::std::os::raw::c_uchar,
    pub rebuilds_num: ::std::os::raw::c_uchar,
    pub entries_start: ::std::os::raw::c_uint,
    pub type_: *const st_hash_type,
    pub num_entries: st_index_t,
    pub entries_bound: st_index_t,
    pub entries: *mut set_table_entry,
}
pub const MISSING_NOENTRY: method_missing_reason = 0;
pub const MISSING_PRIVATE: method_missing_reason = 1;
pub const MISSING_PROTECTED: method_missing_reason = 2;
pub const MISSING_FCALL: method_missing_reason = 4;
pub const MISSING_VCALL: method_missing_reason = 8;
pub const MISSING_SUPER: method_missing_reason = 16;
pub const MISSING_MISSING: method_missing_reason = 32;
pub const MISSING_NONE: method_missing_reason = 64;
pub type method_missing_reason = u32;
pub const METHOD_VISI_UNDEF: rb_method_visibility_t = 0;
pub const METHOD_VISI_PUBLIC: rb_method_visibility_t = 1;
pub const METHOD_VISI_PRIVATE: rb_method_visibility_t = 2;
pub const METHOD_VISI_PROTECTED: rb_method_visibility_t = 3;
pub const METHOD_VISI_MASK: rb_method_visibility_t = 3;
pub type rb_method_visibility_t = u32;
#[repr(C)]
#[repr(align(4))]
#[derive(Debug, Copy, Clone)]
pub struct rb_scope_visi_struct {
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
    pub __bindgen_padding_0: [u8; 3usize],
}
impl rb_scope_visi_struct {
    #[inline]
    pub fn method_visi(&self) -> rb_method_visibility_t {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 3u8) as u32) }
    }
    #[inline]
    pub fn set_method_visi(&mut self, val: rb_method_visibility_t) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 3u8, val as u64)
        }
    }
    #[inline]
    pub fn module_func(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(3usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_module_func(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(3usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        method_visi: rb_method_visibility_t,
        module_func: ::std::os::raw::c_uint,
    ) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 3u8, {
            let method_visi: u32 = unsafe { ::std::mem::transmute(method_visi) };
            method_visi as u64
        });
        __bindgen_bitfield_unit.set(3usize, 1u8, {
            let module_func: u32 = unsafe { ::std::mem::transmute(module_func) };
            module_func as u64
        });
        __bindgen_bitfield_unit
    }
}
pub type rb_scope_visibility_t = rb_scope_visi_struct;
#[repr(C)]
pub struct rb_cref_struct {
    pub flags: VALUE,
    pub refinements: VALUE,
    pub klass_or_self: VALUE,
    pub next: *mut rb_cref_struct,
    pub scope_visi: rb_scope_visibility_t,
}
pub type rb_cref_t = rb_cref_struct;
#[repr(C)]
pub struct rb_method_entry_struct {
    pub flags: VALUE,
    pub defined_class: VALUE,
    pub def: *mut rb_method_definition_struct,
    pub called_id: ID,
    pub owner: VALUE,
}
#[repr(C)]
pub struct rb_callable_method_entry_struct {
    pub flags: VALUE,
    pub defined_class: VALUE,
    pub def: *mut rb_method_definition_struct,
    pub called_id: ID,
    pub owner: VALUE,
}
pub type rb_callable_method_entry_t = rb_callable_method_entry_struct;
pub const VM_METHOD_TYPE_ISEQ: rb_method_type_t = 0;
pub const VM_METHOD_TYPE_CFUNC: rb_method_type_t = 1;
pub const VM_METHOD_TYPE_ATTRSET: rb_method_type_t = 2;
pub const VM_METHOD_TYPE_IVAR: rb_method_type_t = 3;
pub const VM_METHOD_TYPE_BMETHOD: rb_method_type_t = 4;
pub const VM_METHOD_TYPE_ZSUPER: rb_method_type_t = 5;
pub const VM_METHOD_TYPE_ALIAS: rb_method_type_t = 6;
pub const VM_METHOD_TYPE_UNDEF: rb_method_type_t = 7;
pub const VM_METHOD_TYPE_NOTIMPLEMENTED: rb_method_type_t = 8;
pub const VM_METHOD_TYPE_OPTIMIZED: rb_method_type_t = 9;
pub const VM_METHOD_TYPE_MISSING: rb_method_type_t = 10;
pub const VM_METHOD_TYPE_REFINED: rb_method_type_t = 11;
pub type rb_method_type_t = u32;
pub type rb_iseq_t = rb_iseq_struct;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_method_iseq_struct {
    pub iseqptr: *const rb_iseq_t,
    pub cref: *mut rb_cref_t,
}
pub type rb_method_iseq_t = rb_method_iseq_struct;
pub type rb_cfunc_t = ::std::option::Option<unsafe extern "C" fn() -> VALUE>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_method_cfunc_struct {
    pub func: rb_cfunc_t,
    pub invoker: ::std::option::Option<
        unsafe extern "C" fn(
            recv: VALUE,
            argc: ::std::os::raw::c_int,
            argv: *const VALUE,
            func: ::std::option::Option<unsafe extern "C" fn() -> VALUE>,
        ) -> VALUE,
    >,
    pub argc: ::std::os::raw::c_int,
}
pub type rb_method_cfunc_t = rb_method_cfunc_struct;
#[repr(C)]
pub struct rb_method_attr_struct {
    pub id: ID,
    pub location: VALUE,
}
pub type rb_method_attr_t = rb_method_attr_struct;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_method_alias_struct {
    pub original_me: *mut rb_method_entry_struct,
}
pub type rb_method_alias_t = rb_method_alias_struct;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_method_refined_struct {
    pub orig_me: *mut rb_method_entry_struct,
}
pub type rb_method_refined_t = rb_method_refined_struct;
#[repr(C)]
pub struct rb_method_bmethod_struct {
    pub proc_: VALUE,
    pub defined_ractor_id: rb_serial_t,
    pub local_hooks_cnt: ::std::os::raw::c_uint,
}
pub type rb_method_bmethod_t = rb_method_bmethod_struct;
pub const OPTIMIZED_METHOD_TYPE_SEND: method_optimized_type = 0;
pub const OPTIMIZED_METHOD_TYPE_CALL: method_optimized_type = 1;
pub const OPTIMIZED_METHOD_TYPE_BLOCK_CALL: method_optimized_type = 2;
pub const OPTIMIZED_METHOD_TYPE_STRUCT_AREF: method_optimized_type = 3;
pub const OPTIMIZED_METHOD_TYPE_STRUCT_ASET: method_optimized_type = 4;
pub const OPTIMIZED_METHOD_TYPE__MAX: method_optimized_type = 5;
pub type method_optimized_type = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_method_optimized {
    pub type_: method_optimized_type,
    pub index: ::std::os::raw::c_uint,
}
pub type rb_method_optimized_t = rb_method_optimized;
#[repr(C)]
pub struct rb_method_definition_struct {
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
    pub reference_count: rb_atomic_t,
    pub body: rb_method_definition_struct__bindgen_ty_1,
    pub original_id: ID,
    pub original_module: VALUE,
    pub method_serial: usize,
    pub box_: *const rb_box_t,
}
#[repr(C)]
pub struct rb_method_definition_struct__bindgen_ty_1 {
    pub iseq: __BindgenUnionField<rb_method_iseq_t>,
    pub cfunc: __BindgenUnionField<rb_method_cfunc_t>,
    pub attr: __BindgenUnionField<rb_method_attr_t>,
    pub alias: __BindgenUnionField<rb_method_alias_t>,
    pub refined: __BindgenUnionField<rb_method_refined_t>,
    pub bmethod: __BindgenUnionField<rb_method_bmethod_t>,
    pub optimized: __BindgenUnionField<rb_method_optimized_t>,
    pub bindgen_union_field: [u64; 3usize],
}
impl rb_method_definition_struct {
    #[inline]
    pub fn type_(&self) -> rb_method_type_t {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 4u8) as u32) }
    }
    #[inline]
    pub fn set_type(&mut self, val: rb_method_type_t) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 4u8, val as u64)
        }
    }
    #[inline]
    pub fn iseq_overload(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(4usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_iseq_overload(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(4usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn no_redef_warning(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(5usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_no_redef_warning(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(5usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn aliased(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(6usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_aliased(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(6usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        type_: rb_method_type_t,
        iseq_overload: ::std::os::raw::c_uint,
        no_redef_warning: ::std::os::raw::c_uint,
        aliased: ::std::os::raw::c_uint,
    ) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 4u8, {
            let type_: u32 = unsafe { ::std::mem::transmute(type_) };
            type_ as u64
        });
        __bindgen_bitfield_unit.set(4usize, 1u8, {
            let iseq_overload: u32 = unsafe { ::std::mem::transmute(iseq_overload) };
            iseq_overload as u64
        });
        __bindgen_bitfield_unit.set(5usize, 1u8, {
            let no_redef_warning: u32 = unsafe { ::std::mem::transmute(no_redef_warning) };
            no_redef_warning as u64
        });
        __bindgen_bitfield_unit.set(6usize, 1u8, {
            let aliased: u32 = unsafe { ::std::mem::transmute(aliased) };
            aliased as u64
        });
        __bindgen_bitfield_unit
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_code_position_struct {
    pub lineno: ::std::os::raw::c_int,
    pub column: ::std::os::raw::c_int,
}
pub type rb_code_position_t = rb_code_position_struct;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_code_location_struct {
    pub beg_pos: rb_code_position_t,
    pub end_pos: rb_code_position_t,
}
pub type rb_code_location_t = rb_code_location_struct;
#[repr(C)]
pub struct RNode {
    pub flags: VALUE,
    pub nd_loc: rb_code_location_t,
    pub node_id: ::std::os::raw::c_int,
}
pub type NODE = RNode;
pub type rb_nativethread_id_t = pthread_t;
pub type rb_nativethread_lock_t = pthread_mutex_t;
pub type rb_nativethread_cond_t = pthread_cond_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_thread_sched_waiting {
    pub flags: rb_thread_sched_waiting_thread_sched_waiting_flag,
    pub data: rb_thread_sched_waiting__bindgen_ty_1,
    pub node: ccan_list_node,
    pub wheel_lvl: u8,
    pub wheel_slot: u8,
    pub fd_node: ccan_list_node,
}
pub const thread_sched_waiting_none: rb_thread_sched_waiting_thread_sched_waiting_flag = 0;
pub const thread_sched_waiting_timeout: rb_thread_sched_waiting_thread_sched_waiting_flag = 1;
pub const thread_sched_waiting_io_read: rb_thread_sched_waiting_thread_sched_waiting_flag = 2;
pub const thread_sched_waiting_io_write: rb_thread_sched_waiting_thread_sched_waiting_flag = 8;
pub const thread_sched_waiting_io_force: rb_thread_sched_waiting_thread_sched_waiting_flag = 64;
pub type rb_thread_sched_waiting_thread_sched_waiting_flag = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_thread_sched_waiting__bindgen_ty_1 {
    pub timeout: u64,
    pub event_serial: u32,
    pub fd: ::std::os::raw::c_int,
    pub result: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_thread_sched_item {
    pub node: rb_thread_sched_item__bindgen_ty_1,
    pub waiting_reason: rb_thread_sched_waiting,
    pub event_serial: u32,
    pub wake_pending_cnt: u32,
    pub waiting_timed: bool,
    pub malloc_stack: bool,
    pub context_stack: *mut ::std::os::raw::c_void,
    pub context_stack_size: usize,
    pub context: *mut coroutine_context,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_thread_sched_item__bindgen_ty_1 {
    pub ubf: ccan_list_node,
    pub readyq: ccan_list_node,
    pub is_ready: bool,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct rb_native_thread {
    pub serial: rb_atomic_t,
    pub vm: *mut rb_vm_struct,
    pub thread_id: rb_nativethread_id_t,
    pub tid: ::std::os::raw::c_int,
    pub running_thread: *mut rb_thread_struct,
    pub running_th_lock: rb_nativethread_lock_t,
    pub running_th: *mut rb_thread_struct,
    pub snts_node: ccan_list_node,
    pub running_dnts_node: ccan_list_node,
    pub barrier_counted_serial: u32,
    pub readyq: rb_nativethread_cond_t,
    pub altstack: *mut ::std::os::raw::c_void,
    pub nt_context: *mut coroutine_context,
    pub dedicated: ::std::os::raw::c_int,
    pub retiring: bool,
    pub dead_co: *mut coroutine_context,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct rb_thread_sched {
    pub lock_: rb_nativethread_lock_t,
    pub lock_owner: *mut rb_thread_struct,
    pub running: *mut rb_thread_struct,
    pub runnable_hot_th: *mut rb_thread_struct,
    pub runnable_hot_th_waiting: ::std::os::raw::c_int,
    pub is_running: bool,
    pub enable_mn_threads: bool,
    pub readyq: ccan_list_head,
    pub readyq_cnt: ::std::os::raw::c_int,
    pub grq_node: ccan_list_node,
    pub timeslice_node: ccan_list_node,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct rb_ractor_sched {
    pub lock: rb_nativethread_lock_t,
    pub lock_owner: *mut rb_ractor_struct,
    pub locked: bool,
    pub cond: rb_nativethread_cond_t,
    pub snt_cnt: rb_atomic_t,
    pub dnt_cnt: ::std::os::raw::c_uint,
    pub max_cpu: ::std::os::raw::c_uint,
    pub grq: ccan_list_head,
    pub winding_cnt: rb_atomic_t,
    pub grq_cnt: ::std::os::raw::c_uint,
    pub ntlist: rb_ractor_sched__bindgen_ty_1,
    pub timeslice: rb_ractor_sched__bindgen_ty_2,
    pub timeslice_wait_inf: bool,
    pub barrier_complete_cond: rb_nativethread_cond_t,
    pub barrier_release_cond: rb_nativethread_cond_t,
    pub barrier_is_waiting: rb_atomic_t,
    pub barrier_joined_cnt: ::std::os::raw::c_uint,
    pub barrier_running_cnt: ::std::os::raw::c_uint,
    pub barrier_serial: ::std::os::raw::c_uint,
    pub barrier_ractor: *mut rb_ractor_struct,
    pub barrier_lock_rec: ::std::os::raw::c_uint,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct rb_ractor_sched__bindgen_ty_1 {
    pub lock: rb_nativethread_lock_t,
    pub running_dnts: ccan_list_head,
    pub snts: ccan_list_head,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct rb_ractor_sched__bindgen_ty_2 {
    pub lock: rb_nativethread_lock_t,
    pub scheds: ccan_list_head,
}
pub type rb_snum_t = ::std::os::raw::c_long;
pub const RUBY_TAG_NONE: ruby_tag_type = 0;
pub const RUBY_TAG_RETURN: ruby_tag_type = 1;
pub const RUBY_TAG_BREAK: ruby_tag_type = 2;
pub const RUBY_TAG_NEXT: ruby_tag_type = 3;
pub const RUBY_TAG_RETRY: ruby_tag_type = 4;
pub const RUBY_TAG_REDO: ruby_tag_type = 5;
pub const RUBY_TAG_RAISE: ruby_tag_type = 6;
pub const RUBY_TAG_THROW: ruby_tag_type = 7;
pub const RUBY_TAG_FATAL: ruby_tag_type = 8;
pub const RUBY_TAG_MASK: ruby_tag_type = 15;
pub type ruby_tag_type = u32;
pub type rb_compile_option_t = rb_compile_option_struct;
#[repr(C)]
pub struct iseq_inline_constant_cache_entry {
    pub flags: VALUE,
    pub value: VALUE,
    pub ic_cref: *const rb_cref_t,
    pub ractor_id: rb_serial_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct iseq_inline_constant_cache {
    pub entry: *mut iseq_inline_constant_cache_entry,
    pub segments: *const ID,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct iseq_inline_iv_cache_entry {
    pub value: u64,
    pub iv_set_name: ID,
}
#[repr(C)]
pub struct iseq_inline_storage_entry {
    pub once: __BindgenUnionField<iseq_inline_storage_entry__bindgen_ty_1>,
    pub ic_cache: __BindgenUnionField<iseq_inline_constant_cache>,
    pub iv_cache: __BindgenUnionField<iseq_inline_iv_cache_entry>,
    pub bindgen_union_field: [u64; 2usize],
}
#[repr(C)]
pub struct iseq_inline_storage_entry__bindgen_ty_1 {
    pub running_thread: *mut rb_thread_struct,
    pub value: VALUE,
}
#[repr(C)]
pub struct rb_calling_info {
    pub cd: *const rb_call_data,
    pub cc: *const rb_callcache,
    pub block_handler: VALUE,
    pub recv: VALUE,
    pub argc: ::std::os::raw::c_int,
    pub kw_splat: bool,
    pub heap_argv: VALUE,
}
#[repr(C)]
pub struct rb_iseq_location_struct {
    pub pathobj: VALUE,
    pub label: VALUE,
    pub first_lineno: ::std::os::raw::c_int,
    pub node_id: ::std::os::raw::c_int,
    pub code_location: rb_code_location_t,
}
pub type rb_iseq_location_t = rb_iseq_location_struct;
pub type iseq_bits_t = usize;
pub const ISEQ_TYPE_TOP: rb_iseq_type = 0;
pub const ISEQ_TYPE_METHOD: rb_iseq_type = 1;
pub const ISEQ_TYPE_BLOCK: rb_iseq_type = 2;
pub const ISEQ_TYPE_CLASS: rb_iseq_type = 3;
pub const ISEQ_TYPE_RESCUE: rb_iseq_type = 4;
pub const ISEQ_TYPE_ENSURE: rb_iseq_type = 5;
pub const ISEQ_TYPE_EVAL: rb_iseq_type = 6;
pub const ISEQ_TYPE_MAIN: rb_iseq_type = 7;
pub const ISEQ_TYPE_PLAIN: rb_iseq_type = 8;
pub type rb_iseq_type = u32;
pub type rb_jit_func_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut rb_execution_context_struct,
        arg2: *mut rb_control_frame_struct,
    ) -> VALUE,
>;
#[repr(C)]
pub struct rb_iseq_variable {
    pub flip_count: rb_snum_t,
    pub script_lines: VALUE,
    pub coverage: VALUE,
    pub pc2branchindex: VALUE,
    pub original_iseq: *mut VALUE,
}
#[repr(C)]
pub struct rb_iseq_constant_body {
    pub type_: rb_iseq_type,
    pub iseq_size: ::std::os::raw::c_uint,
    pub iseq_encoded: *mut VALUE,
    pub param: rb_iseq_constant_body_rb_iseq_parameters,
    pub location: rb_iseq_location_t,
    pub insns_info: rb_iseq_constant_body_iseq_insn_info,
    pub local_table: *const ID,
    pub lvar_states: rb_iseq_constant_body__bindgen_ty_1,
    pub catch_table: *mut iseq_catch_table,
    pub parent_iseq: *const rb_iseq_struct,
    pub local_iseq: *mut rb_iseq_struct,
    pub is_entries: *mut iseq_inline_storage_entry,
    pub call_data: *mut rb_call_data,
    pub variable: *mut rb_iseq_variable,
    pub local_table_size: ::std::os::raw::c_uint,
    pub ic_size: ::std::os::raw::c_uint,
    pub ise_size: ::std::os::raw::c_uint,
    pub ivc_size: ::std::os::raw::c_uint,
    pub icvarc_size: ::std::os::raw::c_uint,
    pub ci_size: ::std::os::raw::c_uint,
    pub stack_max: ::std::os::raw::c_uint,
    pub builtin_attrs: ::std::os::raw::c_uint,
    pub prism: bool,
    pub jit_ep_escape_recorded: rb_atomic_t,
    pub mark_bits: rb_iseq_constant_body__bindgen_ty_2,
    pub outer_variables: *mut rb_id_table,
    pub mandatory_only_iseq: *const rb_iseq_t,
    pub jit_entry_calls: ::std::os::raw::c_uint,
    pub jit_exception_calls: ::std::os::raw::c_uint,
    pub jit_entry: rb_jit_func_t,
    pub jit_exception: rb_jit_func_t,
    pub jit_payload: *mut ::std::os::raw::c_void,
    pub yjit_calls_at_interv: ::std::os::raw::c_uint,
    pub source_hash: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_iseq_constant_body_rb_iseq_parameters {
    pub flags: rb_iseq_constant_body_rb_iseq_parameters__bindgen_ty_1,
    pub size: ::std::os::raw::c_uint,
    pub lead_num: ::std::os::raw::c_int,
    pub opt_num: ::std::os::raw::c_int,
    pub rest_start: ::std::os::raw::c_int,
    pub post_start: ::std::os::raw::c_int,
    pub post_num: ::std::os::raw::c_int,
    pub block_start: ::std::os::raw::c_int,
    pub opt_table: *const VALUE,
    pub keyword: *const rb_iseq_constant_body_rb_iseq_parameters_rb_iseq_param_keyword,
}
#[repr(C)]
#[repr(align(4))]
#[derive(Debug, Copy, Clone)]
pub struct rb_iseq_constant_body_rb_iseq_parameters__bindgen_ty_1 {
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 2usize]>,
    pub __bindgen_padding_0: u16,
}
impl rb_iseq_constant_body_rb_iseq_parameters__bindgen_ty_1 {
    #[inline]
    pub fn has_lead(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_has_lead(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn has_opt(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(1usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_has_opt(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(1usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn has_rest(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(2usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_has_rest(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(2usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn has_post(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(3usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_has_post(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(3usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn has_kw(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(4usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_has_kw(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(4usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn has_kwrest(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(5usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_has_kwrest(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(5usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn has_block(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(6usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_has_block(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(6usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn ambiguous_param0(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(7usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_ambiguous_param0(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(7usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn accepts_no_kwarg(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(8usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_accepts_no_kwarg(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(8usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn ruby2_keywords(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(9usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_ruby2_keywords(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(9usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn anon_rest(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(10usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_anon_rest(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(10usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn anon_kwrest(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(11usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_anon_kwrest(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(11usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn use_block(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(12usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_use_block(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(12usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn forwardable(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(13usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_forwardable(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(13usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn accepts_no_block(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(14usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_accepts_no_block(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(14usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        has_lead: ::std::os::raw::c_uint,
        has_opt: ::std::os::raw::c_uint,
        has_rest: ::std::os::raw::c_uint,
        has_post: ::std::os::raw::c_uint,
        has_kw: ::std::os::raw::c_uint,
        has_kwrest: ::std::os::raw::c_uint,
        has_block: ::std::os::raw::c_uint,
        ambiguous_param0: ::std::os::raw::c_uint,
        accepts_no_kwarg: ::std::os::raw::c_uint,
        ruby2_keywords: ::std::os::raw::c_uint,
        anon_rest: ::std::os::raw::c_uint,
        anon_kwrest: ::std::os::raw::c_uint,
        use_block: ::std::os::raw::c_uint,
        forwardable: ::std::os::raw::c_uint,
        accepts_no_block: ::std::os::raw::c_uint,
    ) -> __BindgenBitfieldUnit<[u8; 2usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 2usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 1u8, {
            let has_lead: u32 = unsafe { ::std::mem::transmute(has_lead) };
            has_lead as u64
        });
        __bindgen_bitfield_unit.set(1usize, 1u8, {
            let has_opt: u32 = unsafe { ::std::mem::transmute(has_opt) };
            has_opt as u64
        });
        __bindgen_bitfield_unit.set(2usize, 1u8, {
            let has_rest: u32 = unsafe { ::std::mem::transmute(has_rest) };
            has_rest as u64
        });
        __bindgen_bitfield_unit.set(3usize, 1u8, {
            let has_post: u32 = unsafe { ::std::mem::transmute(has_post) };
            has_post as u64
        });
        __bindgen_bitfield_unit.set(4usize, 1u8, {
            let has_kw: u32 = unsafe { ::std::mem::transmute(has_kw) };
            has_kw as u64
        });
        __bindgen_bitfield_unit.set(5usize, 1u8, {
            let has_kwrest: u32 = unsafe { ::std::mem::transmute(has_kwrest) };
            has_kwrest as u64
        });
        __bindgen_bitfield_unit.set(6usize, 1u8, {
            let has_block: u32 = unsafe { ::std::mem::transmute(has_block) };
            has_block as u64
        });
        __bindgen_bitfield_unit.set(7usize, 1u8, {
            let ambiguous_param0: u32 = unsafe { ::std::mem::transmute(ambiguous_param0) };
            ambiguous_param0 as u64
        });
        __bindgen_bitfield_unit.set(8usize, 1u8, {
            let accepts_no_kwarg: u32 = unsafe { ::std::mem::transmute(accepts_no_kwarg) };
            accepts_no_kwarg as u64
        });
        __bindgen_bitfield_unit.set(9usize, 1u8, {
            let ruby2_keywords: u32 = unsafe { ::std::mem::transmute(ruby2_keywords) };
            ruby2_keywords as u64
        });
        __bindgen_bitfield_unit.set(10usize, 1u8, {
            let anon_rest: u32 = unsafe { ::std::mem::transmute(anon_rest) };
            anon_rest as u64
        });
        __bindgen_bitfield_unit.set(11usize, 1u8, {
            let anon_kwrest: u32 = unsafe { ::std::mem::transmute(anon_kwrest) };
            anon_kwrest as u64
        });
        __bindgen_bitfield_unit.set(12usize, 1u8, {
            let use_block: u32 = unsafe { ::std::mem::transmute(use_block) };
            use_block as u64
        });
        __bindgen_bitfield_unit.set(13usize, 1u8, {
            let forwardable: u32 = unsafe { ::std::mem::transmute(forwardable) };
            forwardable as u64
        });
        __bindgen_bitfield_unit.set(14usize, 1u8, {
            let accepts_no_block: u32 = unsafe { ::std::mem::transmute(accepts_no_block) };
            accepts_no_block as u64
        });
        __bindgen_bitfield_unit
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_iseq_constant_body_rb_iseq_parameters_rb_iseq_param_keyword {
    pub num: ::std::os::raw::c_int,
    pub required_num: ::std::os::raw::c_int,
    pub bits_start: ::std::os::raw::c_int,
    pub rest_start: ::std::os::raw::c_int,
    pub table: *const ID,
    pub default_values: *mut VALUE,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct rb_iseq_constant_body_iseq_insn_info {
    pub body: *const iseq_insn_info_entry,
    pub positions_or_succ_index_table: rb_iseq_constant_body_iseq_insn_info__bindgen_ty_1,
    pub size: ::std::os::raw::c_uint,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union rb_iseq_constant_body_iseq_insn_info__bindgen_ty_1 {
    pub positions: *mut ::std::os::raw::c_uint,
    pub succ_index_table: *mut succ_index_table,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union rb_iseq_constant_body__bindgen_ty_1 {
    pub list: *mut u8,
    pub single: [u8; 8usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union rb_iseq_constant_body__bindgen_ty_2 {
    pub list: *mut iseq_bits_t,
    pub single: iseq_bits_t,
}
#[repr(C)]
pub struct rb_iseq_struct {
    pub flags: VALUE,
    pub body: *mut rb_iseq_constant_body,
    pub aux: rb_iseq_struct__bindgen_ty_1,
}
#[repr(C)]
pub struct rb_iseq_struct__bindgen_ty_1 {
    pub compile_data: __BindgenUnionField<*mut iseq_compile_data>,
    pub loader: __BindgenUnionField<rb_iseq_struct__bindgen_ty_1__bindgen_ty_1>,
    pub exec: __BindgenUnionField<rb_iseq_struct__bindgen_ty_1__bindgen_ty_2>,
    pub bindgen_union_field: [u64; 2usize],
}
#[repr(C)]
pub struct rb_iseq_struct__bindgen_ty_1__bindgen_ty_1 {
    pub obj: VALUE,
    pub index: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_iseq_struct__bindgen_ty_1__bindgen_ty_2 {
    pub local_hooks_cnt: ::std::os::raw::c_uint,
    pub global_trace_events: rb_event_flag_t,
}
pub type rb_vm_at_exit_func = ::std::option::Option<unsafe extern "C" fn(arg1: *mut rb_vm_struct)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_at_exit_list {
    pub func: rb_vm_at_exit_func,
    pub next: *mut rb_at_exit_list,
}
pub const hook_list_type_ractor_local: rb_hook_list_type = 0;
pub const hook_list_type_targeted_iseq: rb_hook_list_type = 1;
pub const hook_list_type_targeted_def: rb_hook_list_type = 2;
pub const hook_list_type_global: rb_hook_list_type = 3;
pub type rb_hook_list_type = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_hook_list_struct {
    pub hooks: *mut rb_event_hook_struct,
    pub events: rb_event_flag_t,
    pub running: ::std::os::raw::c_uint,
    pub type_: rb_hook_list_type,
    pub need_clean: bool,
}
pub type rb_hook_list_t = rb_hook_list_struct;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gc_mark_func_data_struct {
    pub data: *mut ::std::os::raw::c_void,
    pub mark_func:
        ::std::option::Option<unsafe extern "C" fn(v: VALUE, data: *mut ::std::os::raw::c_void)>,
    pub checking_shareable: bool,
}
#[repr(C)]
pub struct rb_vm_struct {
    pub self_: VALUE,
    pub ractor: rb_vm_struct__bindgen_ty_1,
    pub main_altstack: *mut ::std::os::raw::c_void,
    pub fork_gen: rb_serial_t,
    pub ubf_async_safe: ::std::os::raw::c_int,
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
    pub special_exceptions: [VALUE; 5usize],
    pub master_box: *mut rb_box_t,
    pub root_box: *mut rb_box_t,
    pub main_box: *mut rb_box_t,
    pub static_ext_inits: st_table,
    pub trap_list: rb_vm_struct__bindgen_ty_2,
    pub global_hooks: rb_hook_list_t,
    pub src_encoding_index: ::std::os::raw::c_int,
    pub once_lock: rb_nativethread_lock_t,
    pub once_cond: rb_nativethread_cond_t,
    pub orig_progname: VALUE,
    pub progname: VALUE,
    pub coverages: VALUE,
    pub cme2counter: VALUE,
    pub me_set: VALUE,
    pub coverage_mode: ::std::os::raw::c_int,
    pub gc: rb_vm_struct__bindgen_ty_3,
    pub at_exit: *mut rb_at_exit_list,
    pub builtin_function_table: *const rb_builtin_function,
    pub ci_table: st_table,
    pub negative_cme_table: rb_id_table,
    pub overloaded_cme_table: st_table,
    pub unused_block_warning_table: set_table,
    pub cc_refinement_set: VALUE,
    pub constant_cache: rb_id_table,
    pub inserting_constant_cache_id: ID,
    pub global_cc_cache_table: [*const rb_callcache; 1023usize],
    pub global_cc_cache_table_used: bool,
    pub default_params: rb_vm_struct__bindgen_ty_4,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct rb_vm_struct__bindgen_ty_1 {
    pub set: ccan_list_head,
    pub terminated_set: ccan_list_head,
    pub cnt: ::std::os::raw::c_uint,
    pub blocking_cnt: ::std::os::raw::c_uint,
    pub main_ractor: *mut rb_ractor_struct,
    pub main_thread: *mut rb_thread_struct,
    pub sync: rb_vm_struct__bindgen_ty_1__bindgen_ty_1,
    pub generic_fields_lock: rb_nativethread_lock_t,
    pub sched: rb_ractor_sched,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct rb_vm_struct__bindgen_ty_1__bindgen_ty_1 {
    pub lock: rb_nativethread_lock_t,
    pub lock_owner: *mut rb_ractor_struct,
    pub lock_rec: ::std::os::raw::c_uint,
    pub terminate_cond: rb_nativethread_cond_t,
    pub terminate_waiting: bool,
}
#[repr(C)]
pub struct rb_vm_struct__bindgen_ty_2 {
    pub cmd: [VALUE; 65usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct rb_vm_struct__bindgen_ty_3 {
    pub global_objspace: *mut rb_global_objspace,
    pub zombie_objspaces: *mut rb_vm_struct__bindgen_ty_3_rb_objspace_zombie,
    pub zombie_objspaces_count: usize,
    pub zombie_objspaces_capa: usize,
    pub zombie_total_pages: usize,
    pub registered_globals: rb_vm_struct__bindgen_ty_3__bindgen_ty_1,
    pub disable_holders: rb_atomic_t,
    pub orphan_merge_pjob: ::std::os::raw::c_uint,
    pub cleanup_objspace: *mut ::std::os::raw::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_vm_struct__bindgen_ty_3_rb_objspace_zombie {
    pub objspace: *mut ::std::os::raw::c_void,
    pub owner_slot: *mut *mut ::std::os::raw::c_void,
    pub owner: *mut rb_ractor_struct,
    pub pages: usize,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct rb_vm_struct__bindgen_ty_3__bindgen_ty_1 {
    pub lock: rb_nativethread_lock_t,
    pub addrs: *mut *mut VALUE,
    pub addrs_cnt: usize,
    pub addrs_capa: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_vm_struct__bindgen_ty_4 {
    pub thread_vm_stack_size: usize,
    pub thread_machine_stack_size: usize,
    pub fiber_vm_stack_size: usize,
    pub fiber_machine_stack_size: usize,
}
impl rb_vm_struct {
    #[inline]
    pub fn running(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_running(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn thread_abort_on_exception(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(1usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_thread_abort_on_exception(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(1usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn thread_report_on_exception(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(2usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_thread_report_on_exception(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(2usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn thread_ignore_deadlock(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(3usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_thread_ignore_deadlock(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(3usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        running: ::std::os::raw::c_uint,
        thread_abort_on_exception: ::std::os::raw::c_uint,
        thread_report_on_exception: ::std::os::raw::c_uint,
        thread_ignore_deadlock: ::std::os::raw::c_uint,
    ) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 1u8, {
            let running: u32 = unsafe { ::std::mem::transmute(running) };
            running as u64
        });
        __bindgen_bitfield_unit.set(1usize, 1u8, {
            let thread_abort_on_exception: u32 =
                unsafe { ::std::mem::transmute(thread_abort_on_exception) };
            thread_abort_on_exception as u64
        });
        __bindgen_bitfield_unit.set(2usize, 1u8, {
            let thread_report_on_exception: u32 =
                unsafe { ::std::mem::transmute(thread_report_on_exception) };
            thread_report_on_exception as u64
        });
        __bindgen_bitfield_unit.set(3usize, 1u8, {
            let thread_ignore_deadlock: u32 =
                unsafe { ::std::mem::transmute(thread_ignore_deadlock) };
            thread_ignore_deadlock as u64
        });
        __bindgen_bitfield_unit
    }
}
pub type rb_vm_t = rb_vm_struct;
#[repr(C)]
pub struct rb_control_frame_struct {
    pub pc: *const VALUE,
    pub sp: *mut VALUE,
    pub _iseq: *const rb_iseq_t,
    pub self_: VALUE,
    pub ep: *const VALUE,
    pub block_code: *const ::std::os::raw::c_void,
    pub jit_return: *mut ::std::os::raw::c_void,
}
pub type rb_control_frame_t = rb_control_frame_struct;
pub const THREAD_RUNNABLE: rb_thread_status = 0;
pub const THREAD_STOPPED: rb_thread_status = 1;
pub const THREAD_STOPPED_FOREVER: rb_thread_status = 2;
pub const THREAD_KILLED: rb_thread_status = 3;
pub type rb_thread_status = u32;
pub type rb_jmpbuf_t = [*mut ::std::os::raw::c_void; 5usize];
pub type rb_vm_tag_jmpbuf_t = rb_jmpbuf_t;
#[repr(C)]
pub struct rb_vm_tag {
    pub tag: VALUE,
    pub retval: VALUE,
    pub buf: rb_vm_tag_jmpbuf_t,
    pub prev: *mut rb_vm_tag,
    pub state: ruby_tag_type,
    pub lock_rec: ::std::os::raw::c_uint,
    pub cfp: *mut rb_control_frame_t,
    pub zjit_frame_active: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_unblock_callback {
    pub func: rb_unblock_function_t,
    pub arg: *mut ::std::os::raw::c_void,
    pub event_serial: rb_atomic_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_mutex_struct {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_fiber_struct {
    _unused: [u8; 0],
}
pub type rb_fiber_t = rb_fiber_struct;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_waiting_list {
    pub next: *mut rb_waiting_list,
    pub thread: *mut rb_thread_struct,
    pub fiber: *mut rb_fiber_struct,
}
#[repr(C)]
pub struct rb_execution_context_struct {
    pub vm_stack: *mut VALUE,
    pub vm_stack_size: usize,
    pub cfp: *mut rb_control_frame_t,
    pub tag: *mut rb_vm_tag,
    pub interrupt_flag: rb_atomic_t,
    pub interrupt_mask: rb_atomic_t,
    pub fiber_ptr: *mut rb_fiber_t,
    pub thread_ptr: *mut rb_thread_struct,
    pub serial: rb_serial_t,
    pub ractor_id: rb_serial_t,
    pub local_storage: *mut rb_id_table,
    pub local_storage_recursive_hash: VALUE,
    pub local_storage_recursive_hash_for_trace: VALUE,
    pub storage: VALUE,
    pub root_lep: *const VALUE,
    pub root_svar: VALUE,
    pub trace_arg: *mut rb_trace_arg_struct,
    pub errinfo: VALUE,
    pub passed_block_handler: VALUE,
    pub raised_flag: u8,
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
    pub private_const_reference: VALUE,
    pub gen_fields_cache: rb_execution_context_struct__bindgen_ty_1,
    pub machine: rb_execution_context_struct__bindgen_ty_2,
    pub assert_critical_section_entered: ::std::os::raw::c_int,
}
#[repr(C)]
pub struct rb_execution_context_struct__bindgen_ty_1 {
    pub obj: VALUE,
    pub fields_obj: VALUE,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_execution_context_struct__bindgen_ty_2 {
    pub stack_start: *mut VALUE,
    pub stack_end: *mut VALUE,
    pub stack_maxsize: usize,
    pub regs: jmp_buf,
}
impl rb_execution_context_struct {
    #[inline]
    pub fn method_missing_reason(&self) -> method_missing_reason {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 8u8) as u32) }
    }
    #[inline]
    pub fn set_method_missing_reason(&mut self, val: method_missing_reason) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 8u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        method_missing_reason: method_missing_reason,
    ) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 8u8, {
            let method_missing_reason: u32 =
                unsafe { ::std::mem::transmute(method_missing_reason) };
            method_missing_reason as u64
        });
        __bindgen_bitfield_unit
    }
}
pub type rb_execution_context_t = rb_execution_context_struct;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_ext_config {
    pub ractor_safe: bool,
}
pub type rb_ractor_t = rb_ractor_struct;
#[repr(C)]
pub struct rb_thread_struct {
    pub lt_node: ccan_list_node,
    pub self_: VALUE,
    pub ractor: *mut rb_ractor_t,
    pub vm: *mut rb_vm_t,
    pub nt: *mut rb_native_thread,
    pub ec: *mut rb_execution_context_t,
    pub sched: rb_thread_sched_item,
    pub mn_schedulable: bool,
    pub serial: rb_atomic_t,
    pub last_status: VALUE,
    pub calling: *mut rb_calling_info,
    pub top_self: VALUE,
    pub top_wrapper: VALUE,
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
    pub priority: i8,
    pub running_time_us: u32,
    pub blocking_region_buffer: *mut ::std::os::raw::c_void,
    pub thgroup: VALUE,
    pub value: VALUE,
    pub pending_interrupt_queue: VALUE,
    pub pending_interrupt_mask_stack: VALUE,
    pub interrupt_lock: rb_nativethread_lock_t,
    pub unblock: rb_unblock_callback,
    pub locking_mutex: VALUE,
    pub keeping_mutexes: *mut rb_mutex_struct,
    pub interrupt_exec_tasks: ccan_list_head,
    pub join_list: *mut rb_waiting_list,
    pub invoke_arg: rb_thread_struct__bindgen_ty_1,
    pub invoke_type: rb_thread_struct_thread_invoke_type,
    pub root_fiber: *mut rb_fiber_t,
    pub scheduler: VALUE,
    pub blocking: ::std::os::raw::c_uint,
    pub name: VALUE,
    pub specific_storage: *mut *mut ::std::os::raw::c_void,
    pub ext_config: rb_ext_config,
}
#[repr(C)]
pub struct rb_thread_struct__bindgen_ty_1 {
    pub proc_: __BindgenUnionField<rb_thread_struct__bindgen_ty_1__bindgen_ty_1>,
    pub func: __BindgenUnionField<rb_thread_struct__bindgen_ty_1__bindgen_ty_2>,
    pub bindgen_union_field: [u64; 3usize],
}
#[repr(C)]
pub struct rb_thread_struct__bindgen_ty_1__bindgen_ty_1 {
    pub proc_: VALUE,
    pub args: VALUE,
    pub kw_splat: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_thread_struct__bindgen_ty_1__bindgen_ty_2 {
    pub func:
        ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void) -> VALUE>,
    pub arg: *mut ::std::os::raw::c_void,
}
pub const thread_invoke_type_none: rb_thread_struct_thread_invoke_type = 0;
pub const thread_invoke_type_proc: rb_thread_struct_thread_invoke_type = 1;
pub const thread_invoke_type_ractor_proc: rb_thread_struct_thread_invoke_type = 2;
pub const thread_invoke_type_func: rb_thread_struct_thread_invoke_type = 3;
pub type rb_thread_struct_thread_invoke_type = u32;
impl rb_thread_struct {
    #[inline]
    pub fn status(&self) -> rb_thread_status {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_status(&mut self, val: rb_thread_status) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub fn main_thread(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(2usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_main_thread(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(2usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn has_dedicated_nt(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(3usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_has_dedicated_nt(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(3usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn to_kill(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(4usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_to_kill(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(4usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn abort_on_exception(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(5usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_abort_on_exception(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(5usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn report_on_exception(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(6usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_report_on_exception(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(6usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn pending_interrupt_queue_checked(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(7usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_pending_interrupt_queue_checked(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(7usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        status: rb_thread_status,
        main_thread: ::std::os::raw::c_uint,
        has_dedicated_nt: ::std::os::raw::c_uint,
        to_kill: ::std::os::raw::c_uint,
        abort_on_exception: ::std::os::raw::c_uint,
        report_on_exception: ::std::os::raw::c_uint,
        pending_interrupt_queue_checked: ::std::os::raw::c_uint,
    ) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 2u8, {
            let status: u32 = unsafe { ::std::mem::transmute(status) };
            status as u64
        });
        __bindgen_bitfield_unit.set(2usize, 1u8, {
            let main_thread: u32 = unsafe { ::std::mem::transmute(main_thread) };
            main_thread as u64
        });
        __bindgen_bitfield_unit.set(3usize, 1u8, {
            let has_dedicated_nt: u32 = unsafe { ::std::mem::transmute(has_dedicated_nt) };
            has_dedicated_nt as u64
        });
        __bindgen_bitfield_unit.set(4usize, 1u8, {
            let to_kill: u32 = unsafe { ::std::mem::transmute(to_kill) };
            to_kill as u64
        });
        __bindgen_bitfield_unit.set(5usize, 1u8, {
            let abort_on_exception: u32 = unsafe { ::std::mem::transmute(abort_on_exception) };
            abort_on_exception as u64
        });
        __bindgen_bitfield_unit.set(6usize, 1u8, {
            let report_on_exception: u32 = unsafe { ::std::mem::transmute(report_on_exception) };
            report_on_exception as u64
        });
        __bindgen_bitfield_unit.set(7usize, 1u8, {
            let pending_interrupt_queue_checked: u32 =
                unsafe { ::std::mem::transmute(pending_interrupt_queue_checked) };
            pending_interrupt_queue_checked as u64
        });
        __bindgen_bitfield_unit
    }
}
pub type rb_thread_t = rb_thread_struct;
#[repr(C)]
pub struct rb_trace_arg_struct {
    pub event: rb_event_flag_t,
    pub ec: *mut rb_execution_context_t,
    pub cfp: *const rb_control_frame_t,
    pub self_: VALUE,
    pub id: ID,
    pub called_id: ID,
    pub klass: VALUE,
    pub data: VALUE,
    pub klass_solved: ::std::os::raw::c_int,
    pub lineno: ::std::os::raw::c_int,
    pub path: VALUE,
}
#[repr(C)]
pub struct rb_ractor_pub {
    pub self_: VALUE,
    pub id: rb_serial_t,
    pub hooks: rb_hook_list_t,
    pub targeted_hooks: st_table,
    pub targeted_hooks_cnt: ::std::os::raw::c_uint,
}
#[repr(C)]
pub struct rb_ractor_sync {
    pub lock: rb_nativethread_lock_t,
    pub locked_by: VALUE,
    pub recv_queue: *mut ractor_queue,
    pub waiters: ccan_list_head,
    pub default_port_value: VALUE,
    pub ports: *mut st_table,
    pub next_port_id: usize,
    pub off_queue_baskets: ccan_list_head,
    pub monitors: ccan_list_head,
    pub successor: *mut rb_ractor_t,
    pub legacy: VALUE,
    pub legacy_exc: bool,
    pub legacy_taken: bool,
}
pub const ractor_created: ractor_status = 0;
pub const ractor_running: ractor_status = 1;
pub const ractor_blocking: ractor_status = 2;
pub const ractor_terminated: ractor_status = 3;
pub type ractor_status = u32;
#[repr(C)]
pub struct rb_ractor_struct {
    pub pub_: rb_ractor_pub,
    pub sync: rb_ractor_sync,
    pub registered_marks: *mut VALUE,
    pub registered_marks_cnt: usize,
    pub registered_marks_capa: usize,
    pub mark_func_data: *mut gc_mark_func_data_struct,
    pub threads: rb_ractor_struct__bindgen_ty_1,
    pub postponed_job_triggered_bits: rb_atomic_t,
    pub thgroup_default: VALUE,
    pub name: VALUE,
    pub loc: VALUE,
    pub status_: ractor_status,
    pub vmlr_node: ccan_list_node,
    pub in_terminated_set: bool,
    pub postmortem: bool,
    pub next_ec_serial: rb_serial_t,
    pub local_storage: *mut st_table,
    pub idkey_local_storage: *mut rb_id_table,
    pub local_storage_store_lock: VALUE,
    pub r_stdin: VALUE,
    pub r_stdout: VALUE,
    pub r_stderr: VALUE,
    pub verbose: VALUE,
    pub debug: VALUE,
    pub malloc_gc_disabled: bool,
    pub main_ractor: bool,
    pub newobj_cache: *mut ::std::os::raw::c_void,
    pub objspace: *mut ::std::os::raw::c_void,
    pub creating_child_objspace: *mut ::std::os::raw::c_void,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct rb_ractor_struct__bindgen_ty_1 {
    pub set: ccan_list_head,
    pub cnt: ::std::os::raw::c_uint,
    pub blocking_cnt: ::std::os::raw::c_uint,
    pub sleeper: ::std::os::raw::c_uint,
    pub sched: rb_thread_sched,
    pub running_ec: *mut rb_execution_context_t,
    pub main: *mut rb_thread_t,
    pub dying_th: *mut rb_thread_t,
    pub terminating: bool,
}
#[repr(C)]
pub struct rb_callinfo_kwarg {
    pub keyword_len: ::std::os::raw::c_int,
    pub references: rb_atomic_t,
    pub keywords: __IncompleteArrayField<VALUE>,
}
#[repr(C)]
pub struct rb_callinfo {
    pub flags: VALUE,
    pub kwarg: *const rb_callinfo_kwarg,
    pub mid: VALUE,
    pub flag: ::std::os::raw::c_uint,
    pub argc: ::std::os::raw::c_uint,
}
pub type vm_call_handler = ::std::option::Option<
    unsafe extern "C" fn(
        ec: *mut rb_execution_context_struct,
        cfp: *mut rb_control_frame_struct,
        calling: *mut rb_calling_info,
    ) -> VALUE,
>;
#[repr(C)]
pub struct rb_callcache {
    pub flags: VALUE,
    pub klass: VALUE,
    pub cme_: *const rb_callable_method_entry_struct,
    pub call_: vm_call_handler,
    pub aux_: rb_callcache__bindgen_ty_1,
}
#[repr(C)]
pub struct rb_callcache__bindgen_ty_1 {
    pub attr: __BindgenUnionField<rb_callcache__bindgen_ty_1__bindgen_ty_1>,
    pub method_missing_reason: __BindgenUnionField<method_missing_reason>,
    pub v: __BindgenUnionField<VALUE>,
    pub bf: __BindgenUnionField<*const rb_builtin_function>,
    pub bindgen_union_field: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_callcache__bindgen_ty_1__bindgen_ty_1 {
    pub value: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_call_data {
    pub ci: *const rb_callinfo,
    pub cc: *const rb_callcache,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_builtin_function {
    pub func_ptr: *const ::std::os::raw::c_void,
    pub argc: ::std::os::raw::c_int,
    pub index: ::std::os::raw::c_int,
    pub name: *const ::std::os::raw::c_char,
}
pub const YARVINSN_nop: ruby_vminsn_type = 0;
pub const YARVINSN_getlocal: ruby_vminsn_type = 1;
pub const YARVINSN_setlocal: ruby_vminsn_type = 2;
pub const YARVINSN_getblockparam: ruby_vminsn_type = 3;
pub const YARVINSN_setblockparam: ruby_vminsn_type = 4;
pub const YARVINSN_getblockparamproxy: ruby_vminsn_type = 5;
pub const YARVINSN_getspecial: ruby_vminsn_type = 6;
pub const YARVINSN_setspecial: ruby_vminsn_type = 7;
pub const YARVINSN_getinstancevariable: ruby_vminsn_type = 8;
pub const YARVINSN_setinstancevariable: ruby_vminsn_type = 9;
pub const YARVINSN_getclassvariable: ruby_vminsn_type = 10;
pub const YARVINSN_setclassvariable: ruby_vminsn_type = 11;
pub const YARVINSN_opt_getconstant_path: ruby_vminsn_type = 12;
pub const YARVINSN_getconstant: ruby_vminsn_type = 13;
pub const YARVINSN_setconstant: ruby_vminsn_type = 14;
pub const YARVINSN_getglobal: ruby_vminsn_type = 15;
pub const YARVINSN_setglobal: ruby_vminsn_type = 16;
pub const YARVINSN_putnil: ruby_vminsn_type = 17;
pub const YARVINSN_putself: ruby_vminsn_type = 18;
pub const YARVINSN_putobject: ruby_vminsn_type = 19;
pub const YARVINSN_putspecialobject: ruby_vminsn_type = 20;
pub const YARVINSN_dupstring: ruby_vminsn_type = 21;
pub const YARVINSN_dupchilledstring: ruby_vminsn_type = 22;
pub const YARVINSN_concatstrings: ruby_vminsn_type = 23;
pub const YARVINSN_anytostring: ruby_vminsn_type = 24;
pub const YARVINSN_toregexp: ruby_vminsn_type = 25;
pub const YARVINSN_intern: ruby_vminsn_type = 26;
pub const YARVINSN_newarray: ruby_vminsn_type = 27;
pub const YARVINSN_pushtoarraykwsplat: ruby_vminsn_type = 28;
pub const YARVINSN_duparray: ruby_vminsn_type = 29;
pub const YARVINSN_duphash: ruby_vminsn_type = 30;
pub const YARVINSN_expandarray: ruby_vminsn_type = 31;
pub const YARVINSN_concatarray: ruby_vminsn_type = 32;
pub const YARVINSN_concattoarray: ruby_vminsn_type = 33;
pub const YARVINSN_pushtoarray: ruby_vminsn_type = 34;
pub const YARVINSN_splatarray: ruby_vminsn_type = 35;
pub const YARVINSN_splatkw: ruby_vminsn_type = 36;
pub const YARVINSN_newhash: ruby_vminsn_type = 37;
pub const YARVINSN_newrange: ruby_vminsn_type = 38;
pub const YARVINSN_pop: ruby_vminsn_type = 39;
pub const YARVINSN_dup: ruby_vminsn_type = 40;
pub const YARVINSN_dupn: ruby_vminsn_type = 41;
pub const YARVINSN_swap: ruby_vminsn_type = 42;
pub const YARVINSN_opt_reverse: ruby_vminsn_type = 43;
pub const YARVINSN_topn: ruby_vminsn_type = 44;
pub const YARVINSN_setn: ruby_vminsn_type = 45;
pub const YARVINSN_adjuststack: ruby_vminsn_type = 46;
pub const YARVINSN_defined: ruby_vminsn_type = 47;
pub const YARVINSN_definedivar: ruby_vminsn_type = 48;
pub const YARVINSN_checkmatch: ruby_vminsn_type = 49;
pub const YARVINSN_checkkeyword: ruby_vminsn_type = 50;
pub const YARVINSN_checktype: ruby_vminsn_type = 51;
pub const YARVINSN_defineclass: ruby_vminsn_type = 52;
pub const YARVINSN_definemethod: ruby_vminsn_type = 53;
pub const YARVINSN_definesmethod: ruby_vminsn_type = 54;
pub const YARVINSN_send: ruby_vminsn_type = 55;
pub const YARVINSN_sendforward: ruby_vminsn_type = 56;
pub const YARVINSN_opt_send_without_block: ruby_vminsn_type = 57;
pub const YARVINSN_opt_new: ruby_vminsn_type = 58;
pub const YARVINSN_objtostring: ruby_vminsn_type = 59;
pub const YARVINSN_opt_ary_freeze: ruby_vminsn_type = 60;
pub const YARVINSN_opt_hash_freeze: ruby_vminsn_type = 61;
pub const YARVINSN_opt_str_freeze: ruby_vminsn_type = 62;
pub const YARVINSN_opt_nil_p: ruby_vminsn_type = 63;
pub const YARVINSN_opt_str_uminus: ruby_vminsn_type = 64;
pub const YARVINSN_opt_duparray_send: ruby_vminsn_type = 65;
pub const YARVINSN_opt_newarray_send: ruby_vminsn_type = 66;
pub const YARVINSN_invokesuper: ruby_vminsn_type = 67;
pub const YARVINSN_invokesuperforward: ruby_vminsn_type = 68;
pub const YARVINSN_invokeblock: ruby_vminsn_type = 69;
pub const YARVINSN_leave: ruby_vminsn_type = 70;
pub const YARVINSN_throw: ruby_vminsn_type = 71;
pub const YARVINSN_jump: ruby_vminsn_type = 72;
pub const YARVINSN_branchif: ruby_vminsn_type = 73;
pub const YARVINSN_branchunless: ruby_vminsn_type = 74;
pub const YARVINSN_branchnil: ruby_vminsn_type = 75;
pub const YARVINSN_jump_without_ints: ruby_vminsn_type = 76;
pub const YARVINSN_branchif_without_ints: ruby_vminsn_type = 77;
pub const YARVINSN_branchunless_without_ints: ruby_vminsn_type = 78;
pub const YARVINSN_branchnil_without_ints: ruby_vminsn_type = 79;
pub const YARVINSN_once: ruby_vminsn_type = 80;
pub const YARVINSN_opt_case_dispatch: ruby_vminsn_type = 81;
pub const YARVINSN_opt_plus: ruby_vminsn_type = 82;
pub const YARVINSN_opt_minus: ruby_vminsn_type = 83;
pub const YARVINSN_opt_mult: ruby_vminsn_type = 84;
pub const YARVINSN_opt_div: ruby_vminsn_type = 85;
pub const YARVINSN_opt_mod: ruby_vminsn_type = 86;
pub const YARVINSN_opt_eq: ruby_vminsn_type = 87;
pub const YARVINSN_opt_neq: ruby_vminsn_type = 88;
pub const YARVINSN_opt_lt: ruby_vminsn_type = 89;
pub const YARVINSN_opt_le: ruby_vminsn_type = 90;
pub const YARVINSN_opt_gt: ruby_vminsn_type = 91;
pub const YARVINSN_opt_ge: ruby_vminsn_type = 92;
pub const YARVINSN_opt_ltlt: ruby_vminsn_type = 93;
pub const YARVINSN_opt_and: ruby_vminsn_type = 94;
pub const YARVINSN_opt_or: ruby_vminsn_type = 95;
pub const YARVINSN_opt_aref: ruby_vminsn_type = 96;
pub const YARVINSN_opt_aset: ruby_vminsn_type = 97;
pub const YARVINSN_opt_length: ruby_vminsn_type = 98;
pub const YARVINSN_opt_size: ruby_vminsn_type = 99;
pub const YARVINSN_opt_empty_p: ruby_vminsn_type = 100;
pub const YARVINSN_opt_succ: ruby_vminsn_type = 101;
pub const YARVINSN_opt_not: ruby_vminsn_type = 102;
pub const YARVINSN_opt_regexpmatch2: ruby_vminsn_type = 103;
pub const YARVINSN_invokebuiltin: ruby_vminsn_type = 104;
pub const YARVINSN_opt_invokebuiltin_delegate: ruby_vminsn_type = 105;
pub const YARVINSN_opt_invokebuiltin_delegate_leave: ruby_vminsn_type = 106;
pub const YARVINSN_getlocal_WC_0: ruby_vminsn_type = 107;
pub const YARVINSN_getlocal_WC_1: ruby_vminsn_type = 108;
pub const YARVINSN_setlocal_WC_0: ruby_vminsn_type = 109;
pub const YARVINSN_setlocal_WC_1: ruby_vminsn_type = 110;
pub const YARVINSN_putobject_INT2FIX_0_: ruby_vminsn_type = 111;
pub const YARVINSN_putobject_INT2FIX_1_: ruby_vminsn_type = 112;
pub const YARVINSN_trace_nop: ruby_vminsn_type = 113;
pub const YARVINSN_trace_getlocal: ruby_vminsn_type = 114;
pub const YARVINSN_trace_setlocal: ruby_vminsn_type = 115;
pub const YARVINSN_trace_getblockparam: ruby_vminsn_type = 116;
pub const YARVINSN_trace_setblockparam: ruby_vminsn_type = 117;
pub const YARVINSN_trace_getblockparamproxy: ruby_vminsn_type = 118;
pub const YARVINSN_trace_getspecial: ruby_vminsn_type = 119;
pub const YARVINSN_trace_setspecial: ruby_vminsn_type = 120;
pub const YARVINSN_trace_getinstancevariable: ruby_vminsn_type = 121;
pub const YARVINSN_trace_setinstancevariable: ruby_vminsn_type = 122;
pub const YARVINSN_trace_getclassvariable: ruby_vminsn_type = 123;
pub const YARVINSN_trace_setclassvariable: ruby_vminsn_type = 124;
pub const YARVINSN_trace_opt_getconstant_path: ruby_vminsn_type = 125;
pub const YARVINSN_trace_getconstant: ruby_vminsn_type = 126;
pub const YARVINSN_trace_setconstant: ruby_vminsn_type = 127;
pub const YARVINSN_trace_getglobal: ruby_vminsn_type = 128;
pub const YARVINSN_trace_setglobal: ruby_vminsn_type = 129;
pub const YARVINSN_trace_putnil: ruby_vminsn_type = 130;
pub const YARVINSN_trace_putself: ruby_vminsn_type = 131;
pub const YARVINSN_trace_putobject: ruby_vminsn_type = 132;
pub const YARVINSN_trace_putspecialobject: ruby_vminsn_type = 133;
pub const YARVINSN_trace_dupstring: ruby_vminsn_type = 134;
pub const YARVINSN_trace_dupchilledstring: ruby_vminsn_type = 135;
pub const YARVINSN_trace_concatstrings: ruby_vminsn_type = 136;
pub const YARVINSN_trace_anytostring: ruby_vminsn_type = 137;
pub const YARVINSN_trace_toregexp: ruby_vminsn_type = 138;
pub const YARVINSN_trace_intern: ruby_vminsn_type = 139;
pub const YARVINSN_trace_newarray: ruby_vminsn_type = 140;
pub const YARVINSN_trace_pushtoarraykwsplat: ruby_vminsn_type = 141;
pub const YARVINSN_trace_duparray: ruby_vminsn_type = 142;
pub const YARVINSN_trace_duphash: ruby_vminsn_type = 143;
pub const YARVINSN_trace_expandarray: ruby_vminsn_type = 144;
pub const YARVINSN_trace_concatarray: ruby_vminsn_type = 145;
pub const YARVINSN_trace_concattoarray: ruby_vminsn_type = 146;
pub const YARVINSN_trace_pushtoarray: ruby_vminsn_type = 147;
pub const YARVINSN_trace_splatarray: ruby_vminsn_type = 148;
pub const YARVINSN_trace_splatkw: ruby_vminsn_type = 149;
pub const YARVINSN_trace_newhash: ruby_vminsn_type = 150;
pub const YARVINSN_trace_newrange: ruby_vminsn_type = 151;
pub const YARVINSN_trace_pop: ruby_vminsn_type = 152;
pub const YARVINSN_trace_dup: ruby_vminsn_type = 153;
pub const YARVINSN_trace_dupn: ruby_vminsn_type = 154;
pub const YARVINSN_trace_swap: ruby_vminsn_type = 155;
pub const YARVINSN_trace_opt_reverse: ruby_vminsn_type = 156;
pub const YARVINSN_trace_topn: ruby_vminsn_type = 157;
pub const YARVINSN_trace_setn: ruby_vminsn_type = 158;
pub const YARVINSN_trace_adjuststack: ruby_vminsn_type = 159;
pub const YARVINSN_trace_defined: ruby_vminsn_type = 160;
pub const YARVINSN_trace_definedivar: ruby_vminsn_type = 161;
pub const YARVINSN_trace_checkmatch: ruby_vminsn_type = 162;
pub const YARVINSN_trace_checkkeyword: ruby_vminsn_type = 163;
pub const YARVINSN_trace_checktype: ruby_vminsn_type = 164;
pub const YARVINSN_trace_defineclass: ruby_vminsn_type = 165;
pub const YARVINSN_trace_definemethod: ruby_vminsn_type = 166;
pub const YARVINSN_trace_definesmethod: ruby_vminsn_type = 167;
pub const YARVINSN_trace_send: ruby_vminsn_type = 168;
pub const YARVINSN_trace_sendforward: ruby_vminsn_type = 169;
pub const YARVINSN_trace_opt_send_without_block: ruby_vminsn_type = 170;
pub const YARVINSN_trace_opt_new: ruby_vminsn_type = 171;
pub const YARVINSN_trace_objtostring: ruby_vminsn_type = 172;
pub const YARVINSN_trace_opt_ary_freeze: ruby_vminsn_type = 173;
pub const YARVINSN_trace_opt_hash_freeze: ruby_vminsn_type = 174;
pub const YARVINSN_trace_opt_str_freeze: ruby_vminsn_type = 175;
pub const YARVINSN_trace_opt_nil_p: ruby_vminsn_type = 176;
pub const YARVINSN_trace_opt_str_uminus: ruby_vminsn_type = 177;
pub const YARVINSN_trace_opt_duparray_send: ruby_vminsn_type = 178;
pub const YARVINSN_trace_opt_newarray_send: ruby_vminsn_type = 179;
pub const YARVINSN_trace_invokesuper: ruby_vminsn_type = 180;
pub const YARVINSN_trace_invokesuperforward: ruby_vminsn_type = 181;
pub const YARVINSN_trace_invokeblock: ruby_vminsn_type = 182;
pub const YARVINSN_trace_leave: ruby_vminsn_type = 183;
pub const YARVINSN_trace_throw: ruby_vminsn_type = 184;
pub const YARVINSN_trace_jump: ruby_vminsn_type = 185;
pub const YARVINSN_trace_branchif: ruby_vminsn_type = 186;
pub const YARVINSN_trace_branchunless: ruby_vminsn_type = 187;
pub const YARVINSN_trace_branchnil: ruby_vminsn_type = 188;
pub const YARVINSN_trace_jump_without_ints: ruby_vminsn_type = 189;
pub const YARVINSN_trace_branchif_without_ints: ruby_vminsn_type = 190;
pub const YARVINSN_trace_branchunless_without_ints: ruby_vminsn_type = 191;
pub const YARVINSN_trace_branchnil_without_ints: ruby_vminsn_type = 192;
pub const YARVINSN_trace_once: ruby_vminsn_type = 193;
pub const YARVINSN_trace_opt_case_dispatch: ruby_vminsn_type = 194;
pub const YARVINSN_trace_opt_plus: ruby_vminsn_type = 195;
pub const YARVINSN_trace_opt_minus: ruby_vminsn_type = 196;
pub const YARVINSN_trace_opt_mult: ruby_vminsn_type = 197;
pub const YARVINSN_trace_opt_div: ruby_vminsn_type = 198;
pub const YARVINSN_trace_opt_mod: ruby_vminsn_type = 199;
pub const YARVINSN_trace_opt_eq: ruby_vminsn_type = 200;
pub const YARVINSN_trace_opt_neq: ruby_vminsn_type = 201;
pub const YARVINSN_trace_opt_lt: ruby_vminsn_type = 202;
pub const YARVINSN_trace_opt_le: ruby_vminsn_type = 203;
pub const YARVINSN_trace_opt_gt: ruby_vminsn_type = 204;
pub const YARVINSN_trace_opt_ge: ruby_vminsn_type = 205;
pub const YARVINSN_trace_opt_ltlt: ruby_vminsn_type = 206;
pub const YARVINSN_trace_opt_and: ruby_vminsn_type = 207;
pub const YARVINSN_trace_opt_or: ruby_vminsn_type = 208;
pub const YARVINSN_trace_opt_aref: ruby_vminsn_type = 209;
pub const YARVINSN_trace_opt_aset: ruby_vminsn_type = 210;
pub const YARVINSN_trace_opt_length: ruby_vminsn_type = 211;
pub const YARVINSN_trace_opt_size: ruby_vminsn_type = 212;
pub const YARVINSN_trace_opt_empty_p: ruby_vminsn_type = 213;
pub const YARVINSN_trace_opt_succ: ruby_vminsn_type = 214;
pub const YARVINSN_trace_opt_not: ruby_vminsn_type = 215;
pub const YARVINSN_trace_opt_regexpmatch2: ruby_vminsn_type = 216;
pub const YARVINSN_trace_invokebuiltin: ruby_vminsn_type = 217;
pub const YARVINSN_trace_opt_invokebuiltin_delegate: ruby_vminsn_type = 218;
pub const YARVINSN_trace_opt_invokebuiltin_delegate_leave: ruby_vminsn_type = 219;
pub const YARVINSN_trace_getlocal_WC_0: ruby_vminsn_type = 220;
pub const YARVINSN_trace_getlocal_WC_1: ruby_vminsn_type = 221;
pub const YARVINSN_trace_setlocal_WC_0: ruby_vminsn_type = 222;
pub const YARVINSN_trace_setlocal_WC_1: ruby_vminsn_type = 223;
pub const YARVINSN_trace_putobject_INT2FIX_0_: ruby_vminsn_type = 224;
pub const YARVINSN_trace_putobject_INT2FIX_1_: ruby_vminsn_type = 225;
pub const YARVINSN_zjit_getinstancevariable: ruby_vminsn_type = 226;
pub const YARVINSN_zjit_setinstancevariable: ruby_vminsn_type = 227;
pub const YARVINSN_zjit_splatkw: ruby_vminsn_type = 228;
pub const YARVINSN_zjit_definedivar: ruby_vminsn_type = 229;
pub const YARVINSN_zjit_send: ruby_vminsn_type = 230;
pub const YARVINSN_zjit_opt_send_without_block: ruby_vminsn_type = 231;
pub const YARVINSN_zjit_objtostring: ruby_vminsn_type = 232;
pub const YARVINSN_zjit_opt_nil_p: ruby_vminsn_type = 233;
pub const YARVINSN_zjit_invokesuper: ruby_vminsn_type = 234;
pub const YARVINSN_zjit_invokeblock: ruby_vminsn_type = 235;
pub const YARVINSN_zjit_opt_plus: ruby_vminsn_type = 236;
pub const YARVINSN_zjit_opt_minus: ruby_vminsn_type = 237;
pub const YARVINSN_zjit_opt_mult: ruby_vminsn_type = 238;
pub const YARVINSN_zjit_opt_div: ruby_vminsn_type = 239;
pub const YARVINSN_zjit_opt_mod: ruby_vminsn_type = 240;
pub const YARVINSN_zjit_opt_eq: ruby_vminsn_type = 241;
pub const YARVINSN_zjit_opt_neq: ruby_vminsn_type = 242;
pub const YARVINSN_zjit_opt_lt: ruby_vminsn_type = 243;
pub const YARVINSN_zjit_opt_le: ruby_vminsn_type = 244;
pub const YARVINSN_zjit_opt_gt: ruby_vminsn_type = 245;
pub const YARVINSN_zjit_opt_ge: ruby_vminsn_type = 246;
pub const YARVINSN_zjit_opt_ltlt: ruby_vminsn_type = 247;
pub const YARVINSN_zjit_opt_and: ruby_vminsn_type = 248;
pub const YARVINSN_zjit_opt_or: ruby_vminsn_type = 249;
pub const YARVINSN_zjit_opt_aref: ruby_vminsn_type = 250;
pub const YARVINSN_zjit_opt_aset: ruby_vminsn_type = 251;
pub const YARVINSN_zjit_opt_length: ruby_vminsn_type = 252;
pub const YARVINSN_zjit_opt_size: ruby_vminsn_type = 253;
pub const YARVINSN_zjit_opt_empty_p: ruby_vminsn_type = 254;
pub const YARVINSN_zjit_opt_succ: ruby_vminsn_type = 255;
pub const YARVINSN_zjit_opt_not: ruby_vminsn_type = 256;
pub const YARVINSN_zjit_opt_regexpmatch2: ruby_vminsn_type = 257;
pub const VM_INSTRUCTION_SIZE: ruby_vminsn_type = 258;
pub type ruby_vminsn_type = u32;
#[repr(C)]
pub struct iseq_compile_data {
    pub err_info: VALUE,
    pub catch_table_ary: VALUE,
    pub iseq_size: ::std::os::raw::c_uint,
    pub iseq_encoded: *mut VALUE,
    pub is_single_mark_bit: bool,
    pub mark_bits: iseq_compile_data__bindgen_ty_1,
    pub start_label: *mut iseq_label_data,
    pub end_label: *mut iseq_label_data,
    pub redo_label: *mut iseq_label_data,
    pub current_block: *const rb_iseq_t,
    pub ensure_node_stack: *mut iseq_compile_data_ensure_node_stack,
    pub node: iseq_compile_data__bindgen_ty_2,
    pub insn: iseq_compile_data__bindgen_ty_3,
    pub in_rescue: bool,
    pub loopval_popped: ::std::os::raw::c_int,
    pub last_line: ::std::os::raw::c_int,
    pub label_no: ::std::os::raw::c_int,
    pub node_level: ::std::os::raw::c_int,
    pub isolated_depth: ::std::os::raw::c_int,
    pub ci_index: ::std::os::raw::c_uint,
    pub ic_index: ::std::os::raw::c_uint,
    pub option: *const rb_compile_option_t,
    pub ivar_cache_table: *mut rb_id_table,
    pub builtin_function_table: *const rb_builtin_function,
    pub root_node: *const NODE,
    pub catch_except_p: bool,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union iseq_compile_data__bindgen_ty_1 {
    pub list: *mut iseq_bits_t,
    pub single: iseq_bits_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct iseq_compile_data__bindgen_ty_2 {
    pub storage_head: *mut iseq_compile_data_storage,
    pub storage_current: *mut iseq_compile_data_storage,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct iseq_compile_data__bindgen_ty_3 {
    pub storage_head: *mut iseq_compile_data_storage,
    pub storage_current: *mut iseq_compile_data_storage,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_compile_option_struct {
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 2usize]>,
    pub debug_level: ::std::os::raw::c_int,
}
impl rb_compile_option_struct {
    #[inline]
    pub fn inline_const_cache(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_inline_const_cache(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn peephole_optimization(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(1usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_peephole_optimization(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(1usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn tailcall_optimization(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(2usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_tailcall_optimization(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(2usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn specialized_instruction(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(3usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_specialized_instruction(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(3usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn operands_unification(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(4usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_operands_unification(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(4usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn instructions_unification(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(5usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_instructions_unification(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(5usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn frozen_string_literal(&self) -> ::std::os::raw::c_int {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(6usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_frozen_string_literal(&mut self, val: ::std::os::raw::c_int) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(6usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub fn debug_frozen_string_literal(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(8usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_debug_frozen_string_literal(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(8usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn coverage_enabled(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(9usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_coverage_enabled(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(9usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        inline_const_cache: ::std::os::raw::c_uint,
        peephole_optimization: ::std::os::raw::c_uint,
        tailcall_optimization: ::std::os::raw::c_uint,
        specialized_instruction: ::std::os::raw::c_uint,
        operands_unification: ::std::os::raw::c_uint,
        instructions_unification: ::std::os::raw::c_uint,
        frozen_string_literal: ::std::os::raw::c_int,
        debug_frozen_string_literal: ::std::os::raw::c_uint,
        coverage_enabled: ::std::os::raw::c_uint,
    ) -> __BindgenBitfieldUnit<[u8; 2usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 2usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 1u8, {
            let inline_const_cache: u32 = unsafe { ::std::mem::transmute(inline_const_cache) };
            inline_const_cache as u64
        });
        __bindgen_bitfield_unit.set(1usize, 1u8, {
            let peephole_optimization: u32 =
                unsafe { ::std::mem::transmute(peephole_optimization) };
            peephole_optimization as u64
        });
        __bindgen_bitfield_unit.set(2usize, 1u8, {
            let tailcall_optimization: u32 =
                unsafe { ::std::mem::transmute(tailcall_optimization) };
            tailcall_optimization as u64
        });
        __bindgen_bitfield_unit.set(3usize, 1u8, {
            let specialized_instruction: u32 =
                unsafe { ::std::mem::transmute(specialized_instruction) };
            specialized_instruction as u64
        });
        __bindgen_bitfield_unit.set(4usize, 1u8, {
            let operands_unification: u32 = unsafe { ::std::mem::transmute(operands_unification) };
            operands_unification as u64
        });
        __bindgen_bitfield_unit.set(5usize, 1u8, {
            let instructions_unification: u32 =
                unsafe { ::std::mem::transmute(instructions_unification) };
            instructions_unification as u64
        });
        __bindgen_bitfield_unit.set(6usize, 2u8, {
            let frozen_string_literal: u32 =
                unsafe { ::std::mem::transmute(frozen_string_literal) };
            frozen_string_literal as u64
        });
        __bindgen_bitfield_unit.set(8usize, 1u8, {
            let debug_frozen_string_literal: u32 =
                unsafe { ::std::mem::transmute(debug_frozen_string_literal) };
            debug_frozen_string_literal as u64
        });
        __bindgen_bitfield_unit.set(9usize, 1u8, {
            let coverage_enabled: u32 = unsafe { ::std::mem::transmute(coverage_enabled) };
            coverage_enabled as u64
        });
        __bindgen_bitfield_unit
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct iseq_insn_info_entry {
    pub line_no: ::std::os::raw::c_int,
    pub node_id: ::std::os::raw::c_int,
    pub events: rb_event_flag_t,
}
pub const CATCH_TYPE_RESCUE: rb_catch_type = 3;
pub const CATCH_TYPE_ENSURE: rb_catch_type = 5;
pub const CATCH_TYPE_RETRY: rb_catch_type = 7;
pub const CATCH_TYPE_BREAK: rb_catch_type = 9;
pub const CATCH_TYPE_REDO: rb_catch_type = 11;
pub const CATCH_TYPE_NEXT: rb_catch_type = 13;
pub type rb_catch_type = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct iseq_catch_table_entry {
    pub type_: rb_catch_type,
    pub iseq: *mut rb_iseq_t,
    pub start: ::std::os::raw::c_uint,
    pub end: ::std::os::raw::c_uint,
    pub cont: ::std::os::raw::c_uint,
    pub sp: ::std::os::raw::c_uint,
}
#[repr(C, packed)]
pub struct iseq_catch_table {
    pub size: ::std::os::raw::c_uint,
    pub entries: __IncompleteArrayField<iseq_catch_table_entry>,
}
#[repr(C)]
#[derive(Debug)]
pub struct iseq_compile_data_storage {
    pub next: *mut iseq_compile_data_storage,
    pub pos: ::std::os::raw::c_uint,
    pub size: ::std::os::raw::c_uint,
    pub buff: __IncompleteArrayField<::std::os::raw::c_char>,
}
pub const RSTRUCT_EMBED_LEN_MASK: ruby_rstruct_flags = 1040384;
pub const RSTRUCT_EMBED_LEN_SHIFT: ruby_rstruct_flags = 13;
pub type ruby_rstruct_flags = usize;
pub const ROBJECT_OFFSET_AS_HEAP_FIELDS: jit_bindgen_constants = 16;
pub const ROBJECT_OFFSET_AS_ARY: jit_bindgen_constants = 16;
pub const RCLASS_OFFSET_PRIME_FIELDS_OBJ: jit_bindgen_constants = 40;
pub const TDATA_OFFSET_FIELDS_OBJ: jit_bindgen_constants = 16;
pub const RUBY_OFFSET_RHASH_IFNONE: jit_bindgen_constants = 16;
pub const RUBY_OFFSET_RHASH_AR_HINT: jit_bindgen_constants = 24;
pub const RUBY_OFFSET_RHASH_AR_PAIRS: jit_bindgen_constants = 32;
pub const RUBY_RHASH_AR_TABLE_MAX_SIZE: jit_bindgen_constants = 8;
pub const RUBY_OFFSET_RSTRING_LEN: jit_bindgen_constants = 16;
pub const RB_SHAPE_FLAG_SHIFT: jit_bindgen_constants = 32;
pub const RUBY_OFFSET_EC_CFP: jit_bindgen_constants = 16;
pub const RUBY_OFFSET_EC_INTERRUPT_FLAG: jit_bindgen_constants = 32;
pub const RUBY_OFFSET_EC_INTERRUPT_MASK: jit_bindgen_constants = 36;
pub const RUBY_OFFSET_EC_THREAD_PTR: jit_bindgen_constants = 48;
pub const RUBY_OFFSET_EC_RACTOR_ID: jit_bindgen_constants = 64;
pub type jit_bindgen_constants = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct coroutine_context {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct succ_index_table {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_event_hook_struct {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rb_global_objspace {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ractor_queue {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct iseq_label_data {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct iseq_compile_data_ensure_node_stack {
    pub _address: u8,
}
extern "C" {
    pub fn rb_bug(fmt: *const ::std::os::raw::c_char, ...) -> !;
    pub fn rb_gc_mark(obj: VALUE);
    pub fn rb_gc_mark_movable(obj: VALUE);
    pub fn rb_gc_location(obj: VALUE) -> VALUE;
    pub fn rb_gc_writebarrier(old: VALUE, young: VALUE);
    pub fn rb_funcall(recv: VALUE, mid: ID, n: ::std::os::raw::c_int, ...) -> VALUE;
    pub static mut rb_cBasicObject: VALUE;
    pub static mut rb_cObject: VALUE;
    pub static mut rb_cArray: VALUE;
    pub static mut rb_cClass: VALUE;
    pub static mut rb_cFalseClass: VALUE;
    pub static mut rb_cHash: VALUE;
    pub static mut rb_cInteger: VALUE;
    pub static mut rb_cModule: VALUE;
    pub static mut rb_cNilClass: VALUE;
    pub static mut rb_cString: VALUE;
    pub static mut rb_cTrueClass: VALUE;
    pub fn rb_utf8_str_new(
        ptr: *const ::std::os::raw::c_char,
        len: ::std::os::raw::c_long,
    ) -> VALUE;
    pub fn rb_shape_id_offset() -> i32;
    pub fn rb_obj_shape_id(obj: VALUE) -> shape_id_t;
    pub fn rb_shape_get_iv_index(shape_id: shape_id_t, id: ID, value: *mut attr_index_t) -> bool;
}
